---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: 'En tant qu"abonné NetApp Keystone STaaS, vous pouvez obtenir un aperçu de vos abonnements depuis NetApp Console ou Digital Advisor.' 
---
= En savoir plus sur le tableau de bord Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le tableau de bord Keystone est la solution idéale pour surveiller, analyser et gérer efficacement vos abonnements Keystone. Grâce à lui, vous pouvez atteindre les objectifs suivants :

* *Surveiller les détails de l'abonnement* : affichez des informations détaillées sur vos abonnements Keystone, notamment les niveaux de service de performance, l'utilisation de la capacité, les actifs et les alertes.
* *Suivez l'utilisation de la capacité et générez des rapports* : Suivez l'utilisation actuelle et historique de la capacité et générez des rapports pour analyser les données d'abonnement et prendre des décisions éclairées.
* *Consultez la chronologie des abonnements* : Restez informé des dates et événements clés en surveillant la chronologie de vos abonnements.
* *Gérer les abonnements* : Soumettez des demandes de modification des niveaux de service de performance ou d'autres paramètres d'abonnement à mesure que vos besoins évoluent.
* *Analyser les volumes et les objets* : obtenez des informations détaillées sur les volumes et les objets de vos abonnements, y compris leur capacité au niveau du volume et de l'objet.




== Accéder au tableau de bord Keystone

Vous pouvez accéder au tableau de bord Keystone via :

* * Console NetApp * : accédez au tableau de bord depuis *Stockage > Keystone > Présentation* dans la console. Pour en savoir plus, consultezlink:../integrations/keystone-console.html["Tableau de bord Keystone dans la console NetApp"^] .
* *Active IQ Digital Advisor* (également connu sous le nom de Digital Advisor) : accédez au tableau de bord depuis *Général > Abonnements Keystone* dans Digital Advisor. Pour en savoir plus, reportez-vous link:../integrations/keystone-aiq.html["Tableau de bord Keystone dans Digital Advisor"^]à la section .




== À propos de la console NetApp

Keystone est accessible via la console NetApp .

La console NetApp fournit une gestion centralisée des services de stockage et de données NetApp dans les environnements locaux et cloud à l'échelle de l'entreprise. La console est requise pour accéder aux services de données NetApp et les utiliser. En tant qu'interface de gestion, il vous permet de gérer de nombreuses ressources de stockage à partir d'une seule interface. Les administrateurs de console peuvent contrôler l’accès au stockage et aux services pour tous les systèmes de l’entreprise.

Vous n’avez pas besoin de licence ni d’abonnement pour commencer à utiliser la console et vous n’encourez des frais que lorsque vous devez déployer des agents de console dans votre cloud pour garantir la connectivité à vos systèmes de stockage ou à vos services de données NetApp . Cependant, certains services de données NetApp accessibles depuis la console sont sous licence ou basés sur un abonnement.

En savoir plus sur lelink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Console NetApp"^] .

Notez ce qui suit :

* Bien que la Console et Digital Advisor offrent certaines fonctionnalités exclusives, la Console fournit des fonctionnalités d'administration pour Keystone, vous permettant de gérer les abonnements et d'effectuer les ajustements nécessaires. Pour en savoir plus, consultez link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-keystone-roles.html["Rôles d'accès Keystone dans la NetApp Console"^].
* Digital Advisor est intégré à la console, vous permettant d'accéder à toutes les fonctionnalités de Digital Advisor , y compris le tableau de bord Keystone , directement depuis la console. Pour en savoir plus, consultezlink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Intégration de Digital Advisor avec NetApp Console"^] .




== Fonctionnalités Keystone dans NetApp Console et Digital Advisor

Le tableau suivant indique la disponibilité des fonctionnalités de la console NetApp et de Digital Advisor, vous aidant à identifier rapidement la plateforme adaptée à vos besoins :

|===


| *Fonctionnalité* | * Console NetApp * | *Conseiller numérique* 


 a| 
link:../integrations/subscriptions-tab.html["Consultez les détails de votre abonnement"]
| Oui | Oui 


 a| 
link:../integrations/current-usage-tab.html["Surveiller l'utilisation actuelle et historique de la capacité"]
| Oui | Oui 


 a| 
link:../integrations/subscription-timeline.html["Suivre le calendrier d'abonnement"]
| Oui | Non 


 a| 
link:../integrations/assets-tab.html["Afficher les actifs associés à un abonnement Keystone"]
| Oui | Oui 


| link:../integrations/assets.html["Afficher les ressources sur plusieurs abonnements Keystone"] | Oui | Non 


 a| 
link:../integrations/monitoring-alerts.html["Afficher et gérer les alertes et les moniteurs"]
| Oui | Non 


 a| 
link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor["Générer des rapports"]
| Oui | Oui 


 a| 
link:../integrations/volumes-objects-tab.html["Afficher les détails des volumes et des objets"]
| Oui | Oui 


 a| 
link:../integrations/performance-tab.html["Affichez les mesures de performances"]
| Non | Oui 
|===
*Informations connexes*

* link:../integrations/dashboard-access.html["Commencez avec le tableau de bord Keystone"]
* link:../integrations/keystone-console.html["Tableau de bord Keystone dans la console NetApp"]
* link:..//integrations/keystone-aiq.html["Tableau de bord Keystone dans Digital Advisor"]

