---
sidebar: sidebar 
permalink: integrations/keystone-aiq.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq 
summary: Keystone et conseiller digital 
---
= Keystone et conseiller digital
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous vous êtes abonné aux services NetApp Keystone, vous pouvez consulter vos rapports d'utilisation et vos graphiques sur le tableau de bord de Digital Advisor.

Digital Advisor vous permet d'afficher les informations relatives au stockage à la demande et les informations sur l'infrastructure NetApp que vous possédez. Grâce à Digital Advisor, vous disposez d'un tableau de bord unique qui vous permet de consulter vos abonnements, vos niveaux de service et votre utilisation de la capacité, tout en créant des rapports détaillés.

Pour plus d'informations sur le widget du tableau de bord Digital Advisor pour Keystone, voir https://docs.netapp.com/us-en/active-iq/task_view_keystone_capacity_utilization.html["Documentation de Digital Advisor"^].

Pour plus d'informations sur le tableau de bord et le reporting Keystone, reportez-vous à link:../integrations/aiq-keystone-details.html["Tableau de bord et reporting des abonnements Keystone"].

Pour plus d'informations sur le flux de données, voir link:../concepts/infra.html["Les outils de suivi"].
