---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Keystone et BlueXP 
---
= Keystone et BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXP est une plateforme complète de surveillance de centaines de sources de données, avec son propre tableau de bord de visualisation interactif. Si vous achetez un service cloud dans le cadre de votre abonnement NetApp Keystone, vous pouvez accéder à ces services et les gérer via BlueXP.

Le tableau de bord BlueXP Digital Advisor offre une vue graphique et des fonctionnalités d'exploration pour surveiller l'utilisation de votre abonnement Keystone et générer des rapports. Pour plus d'informations sur le tableau de bord Digital Advisor et sur Keystone, voir link:../integrations/aiq-keystone-details.html["Tableau de bord et reporting des abonnements Keystone"].

En tant que client Keystone, si vous disposez d'un abonnement Cloud Volumes ONTAP, vous pouvez utiliser les services Keystone pour facturer votre utilisation de Cloud Volumes ONTAP et consulter vos informations de facturation et de consommation via BlueXP.

Pour cela, vous devez créer un ou plusieurs comptes BlueXP et les lier à votre compte Keystone. Pendant que vous achetez un service cloud via Keystone, vous devez fournir les détails de vos comptes BlueXP à votre Keystone Success Manager (KSM). Cela permet de mesurer et de facturer correctement l'utilisation de vos services cloud via votre abonnement Keystone.

Pour en savoir plus sur Keystone et BlueXP, consultez les liens suivants dans les documents BlueXP :

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Abonnement Keystone"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Gestion des abonnements Keystone"^]

