---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents Keystone
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Nouveautés du stockage en tant que service Keystone
      url: "/release-notes/whats-new.html"
    - title: Problèmes résolus
      url: "/release-notes/fixed-issues.html"
    - title: Problèmes connus
      url: "/release-notes/known-issues.html"
    - title: Limites connues
      url: "/release-notes/known-limitations.html"
  - title: Bienvenue dans Keystone
    url: "/concepts/overview.html"
  - title: Installer et configurer Keystone
    entries:
    - title: Qu'est-ce que le collecteur Keystone
      url: "/installation/installation-overview.html"
    - title: Préparez votre système
      entries:
      - title: Configuration requise pour VMware vSphere
        url: "/installation/vapp-prereqs.html"
      - title: Configuration Linux requise
        url: "/installation/linux-prereqs.html"
      - title: Configuration requise pour ONTAP et StorageGRID
        url: "/installation/addl-req.html"
    - title: Installez le collecteur Keystone
      entries:
      - title: Déploiement VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Installation de Linux
        url: "/installation/linux-installation.html"
      - title: Validation automatique de l'intégrité
        url: "/installation/validation.html"
    - title: Configurer le collecteur Keystone
      url: "/installation/configuration.html"
    - title: Contrôle de l'état des systèmes
      url: "/installation/monitor-health.html"
    - title: Mettez à niveau Keystone Collector
      url: "/installation/upgrade.html"
    - title: Configurez AutoSupport pour Keystone
      url: "/installation/asup-config.html"
    - title: Sécurité du collecteur Keystone
      url: "/installation/security.html"
    - title: Données collectées pour la facturation
      url: "/installation/data-collection.html"
  - title: Tableau de bord Keystone
    entries:
    - title: Afficher le tableau de bord Keystone
      url: "/integrations/keystone-aiq.html"
    - title: Afficher les détails d'utilisation et générer des rapports
      url: "/integrations/aiq-keystone-details.html"
    - title: Onglet abonnements
      url: "/integrations/subscriptions-tab.html"
    - title: Onglet utilisation actuelle
      url: "/integrations/current-usage-tab.html"
    - title: Onglet tendances de capacité
      url: "/integrations/capacity-trend-tab.html"
    - title: Volumes et objets
      url: "/integrations/volumes-objects-tab.html"
    - title: Onglet performances
      url: "/integrations/performance-tab.html"
    - title: Onglet actifs
      url: "/integrations/assets-tab.html"
    - title: Gérez les abonnements Keystone à partir de BlueXP
      url: "/integrations/keystone-cm.html"
  - title: Services STaaS Keystone
    entries:
    - title: Mesures et définitions
      url: "/concepts/metrics.html"
    - title: Qualité de service
      url: "/concepts/qos.html"
    - title: Stockage pris en charge
      url: "/concepts/supported-storage-services.html"
    - title: Capacité prise en charge
      url: "/concepts/supported-storage-capacity.html"
    - title: Niveaux de services
      url: "/concepts/service-levels.html"
    - title: Capacité prise en charge pour les niveaux de service
      url: "/concepts/capacity-requirements.html"
    - title: Services d'abonnement Keystone version 1
      url: "/subscription-services-v1.html"
    - title: Services complémentaires
      entries:
      - title: Protection avancée des données
        url: "/concepts/adp.html"
      - title: Tiering des données
        url: "/concepts/data-tiering.html"
      - title: Services optimisés par Equinix
        url: "/concepts/equinix.html"
      - title: Composants non retournables et non volatiles et conformité au SnapLock
        url: "/concepts/nrnvc.html"
      - title: ÉTATS-UNIS Soutien à citoyens (USCS)
        url: "/concepts/uscs.html"
  - title: Facturation
    entries:
    - title: Tarification Keystone
      url: "/concepts/pricing.html"
    - title: Facturation en fonction de la capacité engagement
      url: "/concepts/committed-capacity-billing.html"
    - title: Mesure basée sur la capacité consommée
      url: "/concepts/consumed-capacity-billing.html"
    - title: Facturation en fonction de la consommation en rafale
      url: "/concepts/burst-consumption-billing.html"
    - title: Facturation en fonction des divers types de volume
      url: "/concepts/misc-volume-billing.html"
    - title: Calendriers de facturation
      url: "/concepts/billing-schedules.html"
  - title: Environnements exploités par les partenaires et par les clients
    url: "/concepts/operational-models.html"
  - title: Infrastructure Keystone
    entries:
    - title: Détails de l'infrastructure
      url: "/concepts/infra.html"
    - title: Composants
      url: "/concepts/components.html"
    - title: Flux de données
      url: "/concepts/data-flow.html"
  - title: Centre de support NetApp Global Services
    url: "/concepts/gssc.html"
  - title: Mentions légales
    url: "/legal-notices.html"
