---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents Keystone
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Nouveautés du stockage en tant que service Keystone
      url: "/release-notes/whats-new.html"
    - title: Problèmes résolus
      url: "/release-notes/fixed-issues.html"
    - title: Problèmes connus
      url: "/release-notes/known-issues.html"
    - title: Limites connues
      url: "/release-notes/known-limitations.html"
  - title: Découvrez Keystone
    entries:
    - title: Présentation
      url: "/concepts/overview.html"
    - title: Infrastructure Keystone
      url: "/concepts/infra.html"
    - title: Collecteur Keystone
      url: "/installation/installation-overview.html"
    - title: Composants
      url: "/concepts/components.html"
    - title: Flux de données
      url: "/concepts/data-flow.html"
    - title: Modèles opérationnels
      url: "/concepts/operational-models.html"
  - title: Installer et configurer Keystone
    entries:
    - title: De formation
      entries:
      - title: Infrastructure virtuelle
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP et StorageGRID
        url: "/installation/addl-req.html"
    - title: Installez le collecteur Keystone
      entries:
      - title: Déployez sur VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Installez sous Linux
        url: "/installation/linux-installation.html"
      - title: Validation automatique du logiciel Keystone
        url: "/installation/validation.html"
    - title: Configurer le collecteur Keystone
      url: "/installation/configuration.html"
    - title: Configurez AutoSupport
      url: "/installation/asup-config.html"
    - title: Sécurité du collecteur Keystone
      url: "/installation/security.html"
    - title: Données collectées pour la facturation
      url: "/installation/data-collection.html"
  - title: Contrôle et mise à niveau
    entries:
    - title: Surveillez l'état du collecteur Keystone
      url: "/installation/monitor-health.html"
    - title: Mettez à niveau Keystone Collector
      url: "/installation/upgrade.html"
  - title: Tableau de bord Keystone
    entries:
    - title: Présentation du tableau de bord Keystone
      url: "/integrations/keystone-aiq.html"
    - title: Afficher les détails d'utilisation et générer des rapports
      url: "/integrations/aiq-keystone-details.html"
    - title: Onglet abonnements
      url: "/integrations/subscriptions-tab.html"
    - title: Consommation actuelle
      url: "/integrations/current-usage-tab.html"
    - title: Onglet tendances de consommation
      url: "/integrations/capacity-trend-tab.html"
    - title: Volumes et objets
      url: "/integrations/volumes-objects-tab.html"
    - title: Onglet actifs
      url: "/integrations/assets-tab.html"
    - title: Onglet performances
      url: "/integrations/performance-tab.html"
    - title: Découvrez Keystone et BlueXP
      url: "/integrations/keystone-cm.html"
  - title: Services STaaS Keystone
    entries:
    - title: Mesures et définitions
      url: "/concepts/metrics.html"
    - title: Qualité de service du stockage
      url: "/concepts/qos.html"
    - title: Stockage pris en charge
      url: "/concepts/supported-storage-services.html"
    - title: Capacité prise en charge
      url: "/concepts/supported-storage-capacity.html"
    - title: Niveaux de services
      url: "/concepts/service-levels.html"
    - title: Exigences de capacité pour les niveaux de service
      url: "/concepts/capacity-requirements.html"
    - title: Services d'abonnement Keystone version 1
      url: "/subscription-services-v1.html"
    - title: Services complémentaires
      entries:
      - title: Protection avancée des données
        url: "/concepts/adp.html"
      - title: Tiering des données
        url: "/concepts/data-tiering.html"
      - title: Services optimisés par Equinix
        url: "/concepts/equinix.html"
      - title: Composants non retournables et non volatiles, et conformité SnapLock
        url: "/concepts/nrnvc.html"
      - title: ÉTATS-UNIS Soutien à citoyens (USCS)
        url: "/concepts/uscs.html"
  - title: SLA de STaaS Keystone
    entries:
    - title: Disponibilité
      url: "/concepts/sla-availability.html"
    - title: Performance
      url: "/concepts/sla-performance.html"
    - title: Durabilité
      url: "/concepts/sla-sustainability.html"
    - title: Garantie de restauration contre les ransomwares
      url: "/concepts/sla-ransomware.html"
  - title: Keystone en mode privé
    entries:
    - title: Présentation
      url: "/dark-sites/overview.html"
    - title: Avant l'installation
      url: "/dark-sites/requirements.html"
    - title: Installez le collecteur Keystone
      url: "/dark-sites/install-collector.html"
    - title: Configurer le collecteur Keystone
      url: "/dark-sites/configure-collector.html"
    - title: Surveillez l'état du collecteur Keystone
      url: "/dark-sites/monitor.html"
  - title: Facturation
    entries:
    - title: Tarification Keystone
      url: "/concepts/pricing.html"
    - title: Facturation en fonction de la capacité engagement
      url: "/concepts/committed-capacity-billing.html"
    - title: Mesure basée sur la capacité consommée
      url: "/concepts/consumed-capacity-billing.html"
    - title: Facturation en fonction de la consommation en rafale
      url: "/concepts/burst-consumption-billing.html"
    - title: Scénarios divers pour la facturation Keystone
      url: "/concepts/misc-volume-billing.html"
    - title: Calendriers de facturation
      url: "/concepts/billing-schedules.html"
  - title: Obtenez de l'aide avec Keystone
    url: "/concepts/gssc.html"
  - title: Mentions légales
    url: "/legal-notices.html"
