---
sidebar: sidebar 
permalink: rest-api/get-customer-consumption.html 
keywords: api, consumption, subscriptions, customerID, keystone, Digital Advisor 
summary: 'L"API REST de Digital Advisor récupère les détails de consommation actuels pour tous les abonnements associés à l"ID de client donné.' 
---
= Obtenez les détails de consommation des clients à l'aide de l'API REST de Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette API récupère les détails de consommation actuelle pour tous les abonnements associés à l'ID de client donné.

*Demande:*

[cols="24%,76%"]
|===


| *Méthode* | OBTENEZ 


| *Point final* | `https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details` 


| *Paramètres*  a| 
* type : « client »
* id : <customer-id>




| *En-têtes*  a| 
* accepter : application/json
* AutorizationToken: <access_key>


|===
*Réponse:* l'API répond avec un objet JSON contenant une liste de toutes les souscriptions avec les mesures d'utilisation de service actuelles pour le client donné. Voici un exemple de réponse :

[listing]
----
{
"result":  {
"returned_records": "string",
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "string",
"end_date": "string"
},
"service_levels": [
{
"name": "string",
"committed_tib": "string",
"consumed_tib": "string",
"consumed_timestamp_utc": "string",
"burst_tib": "string",
"accrued_burst_tib": "string"
}
]
}
],
"request_id": "string",
"response_time": "string"
}
}
----
*Code d'état*: 200 – demande réussie

*Exemple Curl* :

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details?type=customer&id=<customerID>' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----


== Consultez l'historique de consommation d'un client

Cette API récupère les détails de consommation historiques pour tous les abonnements associés à l'ID de client donné, conformément à la plage de temps spécifiée.

*Demande:*

[cols="24%,76%"]
|===


| *Méthode* | OBTENEZ 


| *Point final* | `https://api.activeiq.netapp.com/v1/keystone/customer/historical-consumption-details` 


| *Paramètres*  a| 
* type : « client »
* id : <customer-id>
* From_date_utc : <date de début (au format RFC3339)>
* To_date_utc : <date de fin (au format RFC3339)>




| *En-têtes*  a| 
* accepter : application/json
* AutorizationToken: <access_key>


|===
*Réponse :*

L'API répond avec un objet JSON contenant une liste de tous les abonnements avec les metrics d'utilisation des services historiques pour le client donné dans la plage de temps sélectionnée. Voici un exemple de réponse :

[listing]
----
{
"results":  {
"returned_records": 0,
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "2023-08-24T14:15:22Z",
"end_date": "2023-08-24T14:15:22Z"
},
"service_levels": [
{
"name": "string",
"historical_consumption": [
{
"committed_tib": 0,
"consumed_tib": 0,
"timestamp_utc": "2023-08-24T14:15:22Z",
"burst_tib": 0,
"accrued_burst_tib": 0,
"is_invoiced": true
}
]
}
]
}
],
"request_parameters":  {
"from_date_utc": "2023-08-24",
"to_date_utc": "2023-08-24",
"customer_id": "string"
},
"request_id": "string",
"response_time": "string",
"customer":  {
"name": "string",
"id": "string"
}
}
}
----
*Code d'état*: 200 – demande réussie

*Exemple Curl* :

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq-stg.netapp.com/v1/keystone/customer/historical-consumption-details? type=customer&id=<customerID>&from_date_utc=2023-08-24T14%3A15%3A22Z&t _date_utc=2023-08-24T14%3A15%3A22Z' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----