---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Les abonnements Keystone STaaS sont facturés mensuellement, trimestriellement, semestriellement ou annuellement. 
---
= Découvrez les calendriers de facturation de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les abonnements Keystone STaaS sont facturés sur une base mensuelle, trimestrielle, semestrielle ou annuelle.



== Facturation mensuelle

Les factures sont envoyées chaque mois. Pour le mois au cours duquel les services sont disponibles, une facture est envoyée le mois suivant. Par exemple, la facture des services que vous avez utilisés en janvier est livrée au début de février. Cette facture comprend les frais liés à la capacité engagée et, le cas échéant, à l'utilisation en rafale.



== Facturation trimestrielle, semestrielle et annuelle

Pour la facturation trimestrielle, semestrielle et annuelle, le processus est similaire avec de légères variations de calendrier :

* *Facturation trimestrielle* : Une facture est générée au début de chaque trimestre d'abonnement pour le paiement minimum de la capacité engagée. Une autre facture est envoyée en fin de trimestre pour toute utilisation en rafale cumulée.
* *Facturation semestrielle* : Une facture est générée au début de chaque semestre pour le paiement minimum de la capacité engagée.  Une autre facture est envoyée à la fin de chaque trimestre pour toute utilisation supplémentaire accumulée.
* *Facturation annuelle* : Une facture est générée au début de chaque année d'abonnement pour le paiement minimum de la capacité engagée.  Une autre facture est envoyée à la fin de chaque trimestre pour toute utilisation supplémentaire accumulée.


Pour la facturation trimestrielle, semestrielle et annuelle, si la capacité engagée est modifiée au cours d'un abonnement, une facture est envoyée le même jour pour les paiements minimums au prorata pour le reste de cette année d'abonnement.  La facturation est calculée à partir du jour où le changement de capacité engagée devient effectif.
