---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: Facturation en fonction de la consommation en rafale 
---
= Facturation en fonction de la consommation en rafale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'STaaS (NetApp Keystone) s'appuie sur la capacité d'rafale, c'est-à-dire la capacité consommée par votre entreprise, en plus de la capacité validée des niveaux de service de votre abonnement.

Votre limite de rafale est déterminée et spécifiée dans votre contrat Keystone. Généralement, il dépasse de 20 % la capacité validée.

La capacité dédiée correspond à la capacité engagée pour un niveau de service donné lors de l'achat de l'abonnement. La capacité consommée est la capacité que vos charges de travail utilisent réellement. Lorsque la capacité consommée est supérieure à la capacité engagée pour un niveau de services, la consommation en rafale est enregistrée et facturée en conséquence. Généralement, il dépasse de 20 % la capacité validée pour un niveau de service. L'utilisation au-dessus de la capacité de rafale est indiquée comme « au-dessus de la limite de rafale ».

Ce processus se produit pour chaque enregistrement de consommation généré. La consommation en rafale reflète donc à la fois le montant et la durée de vos capacités surconsommées en plus de vos capacités engagées.

Pour plus d'informations sur les différentes capacités prises en charge par Keystone, reportez-vous à link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"].
