---
sidebar: sidebar 
permalink: concepts/committed-capacity-billing.html 
keywords: Billing based on committed capacity, committed capacity billing 
summary: Capacités de stockage prises en charge 
---
= Facturation en fonction de la capacité engagement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La facturation de NetApp Keystone (Keystone) repose sur la capacité dont vous avez besoin dans le cadre de l'abonnement Keystone.

La capacité dédiée correspond à la capacité engagée pour un niveau de service donné lors de l'achat de l'abonnement. La capacité engagée peut être la capacité totale pour les différents niveaux de service dans un seul abonnement, comme vous l'avez accepté par vous et NetApp/partenaire. Cette capacité est indiquée sur chaque commande Keystone et est facturée, indépendamment de la consommation de la capacité réelle.

Pour plus d'informations sur les différentes capacités prises en charge par Keystone, reportez-vous à link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"].
