---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: 'Découvrez les composants nécessaires à l"activation des services NetApp Keystone STaaS dans votre environnement.' 
---
= Composants requis pour le déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Plusieurs composants sont nécessaires pour activer les services NetApp Keystone STaaS dans votre environnement. Avant de commencer, passez en revue les détails de ces composants.



== Exigences du site

Il existe certaines exigences spécifiques au site, telles que l'espace, les racks, les PDU, l'alimentation, et le refroidissement, avec des exigences supplémentaires en matière de réseau et de sécurité abordées ici.



=== Espace

Espace au sol nécessaire pour héberger l'équipement d'infrastructure Keystone (à fournir par les clients). NetApp fournit les spécifications de poids en fonction de la configuration finale.



=== Portoirs

Quatre porte-vêtements à poste dans l'offre gérée par le client (à fournir par les clients). Dans l'offre gérée par NetApp, NetApp ou le client peuvent fournir les racks, selon les besoins. NetApp fournit 42 racks complets.



=== PDU

Vous devez fournir les unités de distribution de l'alimentation (PDU), connectées à deux circuits distincts protégés avec suffisamment de prises C13. Dans l'offre gérée par le client, dans certains cas, des points de vente C19 sont requis. Dans l'offre exploitée par NetApp, NetApp ou le client peuvent fournir les PDU, selon les exigences.



=== Puissance

Vous devez fournir l'alimentation requise. NetApp fournit les spécifications relatives à la consommation électrique en fonction de la tension nominale de 200 V (typique A, Max A, typique W, Max W, type de cordon d'alimentation, et quantité), en fonction de la configuration finale. Tous les composants disposent d'une alimentation redondante. NetApp fournit les câbles d'alimentation de l'armoire.



=== Refroidissement

NetApp peut fournir les spécifications relatives à la climatisation (BTU typique, BTU max.) en fonction de la configuration et des exigences finales.



=== Ordinateurs virtuels

Des machines virtuelles sont requises pour le déploiement du collecteur Keystone et du collecteur ITOM. Pour connaître les conditions préalables à l'installation, reportez-vous aux sections link:../installation/installation-overview.html["Guide d'installation de Keystone Collector"] et link:../installation/itom-prereqs.html["Conditions requises pour l'installation du collecteur ITOM"]. Les autres exigences sont partagées lors du déploiement.



=== Options de déploiement

Keystone Collector peut être déployé via les méthodes suivantes :

* Modèle VMware OVA (VMware vCenter Server 6.7 ou version ultérieure requis)
* Le client fournit un serveur Linux fonctionnant sous l'un des systèmes d'exploitation suivants : Debian 12, Red Hat Enterprise Linux 8.6 ou versions ultérieures 8.x, Red Hat Enterprise Linux 9.0 ou versions ultérieures, ou CentOS 7 (pour les environnements existants uniquement). Le logiciel Keystone est installé à l'aide de `.deb` ou `.rpm` paquet, selon la distribution Linux.


Le collecteur ITOM peut être déployé via les méthodes suivantes :

* Le client fournit un serveur Linux fonctionnant sous Debian 12, Ubuntu 20.04 LTS, Red Hat Enterprise Linux (RHEL) 8.x, Red Hat Enterprise Linux 9.0, Amazon Linux 2023 ou des versions plus récentes.
* Le client fournit un serveur Windows exécutant Windows Server 2016 ou des versions plus récentes.
+

TIP: Les systèmes d'exploitation recommandés sont Debian 12, Windows Server 2016 ou des versions plus récentes.





=== Mise en réseau

L'accès sortant à _Keystone.NetApp.com_ est requis pour les mises à jour logicielles et les téléchargements de données d'utilisation, essentiels pour le fonctionnement et la maintenance du collecteur Keystone et de la passerelle de la solution AIOps.

Selon les besoins du client et les contrôleurs de stockage utilisés, NetApp offre une connectivité de 10 Go, 40 Go et 100 Go sur le site du client.

NetApp fournit uniquement les émetteurs-récepteurs requis pour les dispositifs d'infrastructure fournis par NetApp. Vous devez fournir les émetteurs-récepteurs requis pour les périphériques du client et le câblage aux périphériques d'infrastructure Keystone fournis par NetApp.



== Besoin d'accès à distance

La connectivité réseau est requise entre l'infrastructure de stockage installée dans le data Center du client ou des services en colocation détenus par le client et le centre d'exploitation Keystone. Le client doit fournir les ressources de calcul, les machines virtuelles et les services Internet. Le client est également responsable de l'application de correctifs pour le système d'exploitation (déploiements non basés sur OVA) et du renforcement de la sécurité en fonction des stratégies de sécurité internes. La conception du réseau doit se faire via un protocole sécurisé, et les politiques de pare-feu seront approuvées par NetApp et par les clients.

NetApp doit accéder aux composants matériels et logiciels installés à des fins de contrôle et de gestion, afin de fournir des services tels que la surveillance et la facturation aux clients Keystone. La méthode la plus courante consiste à établir une connexion VPN (réseau privé virtuel) au réseau du client et à accéder aux données requises. Pour surmonter toute complexité opérationnelle perçue par les clients à l'origine de l'ouverture de ports pare-feu à de nouveaux services, les outils de surveillance lancent une connexion externe. Les applications cloud NetApp, telles que la solution de surveillance ITOM et Zuora, utilisent cette connexion pour exécuter leurs services respectifs. Cette méthode répond aux exigences du client quant à la non-ouverture des ports de pare-feu, mais elle fournit l'accès aux composants de surveillance qui font partie de ce service.
