---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Le service complémentaire de Tiering des données identifie les données moins fréquemment utilisées et les hiérarchise en stockage pris en charge. 
---
= En savoir plus sur le Tiering des données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les services standard Keystone STaaS pour le stockage des fichiers et blocs incluent des fonctionnalités de Tiering qui identifient les données moins utilisées et les répartissent à l'aide de Keystone STaaS (stockage à froid NetApp pris en charge). Si vous souhaitez transférer vos données inactives vers un stockage Keystone STaaS non NetApp, le Tiering des données inactives est possible en tant que service complémentaire.

voir link:../concepts/service-levels.html["Niveaux de service de performance dans Keystone"] .


NOTE: Le service complémentaire de hiérarchisation est requis uniquement lorsque les données sont hiérarchisées vers un stockage non NetApp tel qu'Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) et d'autres stockages d'objets tiers compatibles S3 et pris en charge par Keystone STaaS.

La fonctionnalité de Tiering exploite la technologie NetApp FabricPool pour le Tiering automatisé des données peu utilisées vers des tiers de stockage objet sur site et hors site.

Le service complémentaire de hiérarchisation des données permet la hiérarchisation des niveaux Extreme, Premium, Performance, Standard et Value vers une cible de stockage d'objets. Le ratio de données chaudes et froides à hiérarchiser n'est pas fixe, et chaque niveau est mesuré et facturé séparément.

Par exemple, si la cible pour le Tier de stockage à froid est :

* Niveau de valeur Keystone STaaS, niveau d'objet Keystone STaaS StorageGRID ou grille StorageGRID Webscale (SGWS) existante (appartenant au client) - Il n'y a pas de frais supplémentaires ; cela fait partie du service standard.
* Cloud public (AWS, Azure, Google) ou stockage objet tiers pris en charge par Keystone : des frais supplémentaires sont facturés pour la capacité de données à Tier vers les cibles de stockage à froid.


Les services de Tiering supplémentaires s'appliquent pendant toute la durée de l'abonnement.


NOTE: Les services de calcul, de stockage et de réseau basés sur un hyperscaler requis par Cloud Volumes ONTAP ne sont pas fournis par NetApp dans le cadre des abonnements Keystone STaaS ; ces services doivent être achetés directement auprès des fournisseurs de services cloud hyperscaler.

*Informations connexes*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Comment estimer la consommation de Keystone avec le Tiering des données (FabricPool) à l'aide de l'interface de ligne de commande ONTAP"^]
