---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Add-on, Détails des services supplémentaires, Tiering des données 
---
= Tiering des données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les services standard Keystone STaaS pour le stockage des fichiers et blocs incluent des fonctionnalités de Tiering qui identifient les données moins utilisées et les répartissent à l'aide de Keystone STaaS (stockage à froid NetApp pris en charge). Vous pouvez bénéficier du Tiering des données à titre d'extension si vous souhaitez transférer vos données inactives vers un stockage non NetApp Keystone STaaS pris en charge.

Pour plus d'informations sur les services standard et complémentaires, reportez-vous à la section link:../concepts/supported-storage-services.html["Services STaaS Keystone"]. Pour plus d'informations sur les niveaux de service, reportez-vous à la section link:../concepts/service-levels.html["Niveaux de service dans Keystone"].

Le service d'extension de Tiering est requis uniquement lorsque les données sont envoyées vers un stockage non-NetApp, tel qu'Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP), et d'autres systèmes de stockage objet tiers compatible Keystone STaaS, compatible S3.

La fonctionnalité de Tiering exploite la technologie NetApp FabricPool pour le Tiering automatisé des données peu utilisées vers des tiers de stockage objet sur site et hors site.

Avec le service complémentaire de Tiering des données, vous pouvez effectuer le Tiering à partir de Extreme, Premium, Performance, Standard et Value Tier de stockage objet. Le rapport entre les données actives et inactives à hiérarchiser n'est pas fixe et chaque Tier est mesuré et facturé séparément.

Par exemple, si la cible pour le Tier de stockage à froid est :

* Tier de valeur STaaS Keystone, Tier objet StorageGRID STaaS Keystone ou grid SGWS existant (propriété du client) : il n'y a pas de frais supplémentaires et fait partie du service standard.
* Cloud public (AWS, Azure, Google) ou stockage objet tiers pris en charge par Keystone : des frais supplémentaires sont facturés pour la capacité de données à Tier vers les cibles de stockage à froid.


Les services de Tiering supplémentaires s'appliquent pendant toute la durée de l'abonnement.


NOTE: Les services de calcul, de stockage et de réseau basés sur des hyperscalers requis par Cloud Volumes ONTAP ne sont pas fournis par NetApp dans le cadre d'abonnements Keystone. Ces services doivent être achetés directement auprès de fournisseurs de services cloud hyperscales.
