---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Global Services Support Center, GSSC, Keystone support 
summary: Centre de support NetApp Global Services GSSC 
---
= Centre de support NetApp Global Services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les services NetApp Keystone sont gérés en utilisant le centre NetApp Global Services and support Center (GSSC), le responsable NetApp Keystone Success Manager et le responsable de prestation de services NetApp Keystone.



== Centre de support et de services NetApp (GSSC)

NetApp propose des services d'exploitation à distance aux clients NetApp Keystone. Ces services englobent diverses disciplines opérationnelles dans l'ensemble des activités de gestion du stockage. Il s'agit notamment de la gestion des ressources et de la configuration, de la gestion de la capacité et des performances, de la gestion des changements, des événements, de la gestion des incidents et des problèmes, de l'exécution des demandes de service et des rapports. NetApp démontre son état de contrôle et témoigne de l'existence au besoin.



== Informations supplémentaires et coordonnées de l'assistance

L'équipe du Centre de support et de services NetApp (GSSC) soutient principalement les services fournis aux clients NetApp Keystone. Vous pouvez utiliser les informations suivantes pour contacter l'équipe de support.

* Contacts du service mondial :https://www.netapp.com/us/contact-us/support.aspx[]
* Si votre dossier/ticket ouvert doit être réaffecté de la manière suivante, envoyez un e-mail à l'une des adresses suivantes : keystone.services@netapp.com keystone.escalations@netapp.com
* NetApp utilise Opsrampe, une solution de passerelle cloud à distance pour surveiller de manière proactive l'environnement NetApp Keystone et se connecter à celui-ci pour le dépannage. Pour plus d'informations sur OpsRamp, reportez-vous à la section https://www.opsramp.com/#[].



NOTE: Dans un modèle opéré par les partenaires, les demandes de service des locataires et des sous-locataires sont attribuées au centre de service du partenaire. L'outil de support du partenaire pourrait être intégré aux applications OpsRamp et GSSC. Seuls les problèmes de niveau 3 sont transmis à NetApp via le GSSC.

Pour plus d'informations, voir :

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentation produit NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Surveillance GSSC

Le centre de support et de services NetApp Global Services (GSSC) surveille l'état de vos produits et services abonnés, fournit un support à distance et collabore avec votre responsable de la réussite Keystone. Toutes les personnes qui surveillent les produits associés aux bons d'abonnement Keystone appartiennent aux États-Unis au américain.

Le responsable réussite de Keystone est une Vivant sur le sol américain. Les responsabilités sont précisées dans votre contrat NetApp Keystone.

Pour plus d'informations, reportez-vous à la section link:../concepts/uscs.html["ÉTATS-UNIS Soutien à citoyens (USCS)"].
