---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Découvrez la facturation Keystone pour des configurations spécifiques, notamment les volumes clonés, la protection avancée des données et bien plus encore. 
---
= Découvrez la facturation Keystone pour des configurations de volume spécifiques.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprendre la facturation Keystone pour des configurations spécifiques peut vous aider à optimiser l’utilisation du service et à gérer les coûts. Les configurations incluent des volumes clonés, des volumes temporaires, des destinations SnapMirror , des LUN et des volumes système/racine.



== Facturation des volumes clonés

Si les volumes sont clonés dans ONTAP et que vous les utilisez pour la sauvegarde et la restauration de vos données, vous pouvez continuer à utiliser ces clones sans paiements supplémentaires. Toutefois, les volumes clonés utilisés à d'autres fins dans votre entreprise pendant une durée étendue sont facturés.

Notez ce qui suit :

* Les volumes clones sont libres de se charger tant que leur taille est inférieure à 10 % du volume parent (capacité physique utilisée dans le volume clone par rapport à la capacité physique utilisée dans le volume parent).
* Il n'existe pas de délai de grâce de 24 heures pour les volumes clonés. Seule la taille du clone est prise en compte.
* Une fois que le volume clone dépasse 10 % de la taille physique du parent, le clone est facturé comme volume standard (capacité logique utilisée).




== Facturation des volumes temporaires

Il arrive que des volumes temporaires soient créés par ONTAP lors du déplacement de volumes. Ces volumes temporaires sont de courte durée, et la consommation sur ces volumes n'est pas mesurée pour la facturation.



== Facturation des destinations SnapMirror

La tarification des volumes de destination SnapMirror, qu'ils soient utilisés pour la reprise après sinistre ou la conservation à long terme, est basée sur le niveau de service de performance attribué à la destination. Aucun frais supplémentaire n'est appliqué pour la protection des données.



== Facturation des LUN

Pour les LUN, la facturation est basée sur les niveaux de service de performance du volume.



== Volumes racine et système

Les volumes système et racine sont surveillés dans le cadre du contrôle global du service Keystone, mais ne sont pas comptabilisés ou facturés. La consommation sur ces volumes est exemptée de la facturation.
