---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes 
summary: Les règles de facturation de Keystone varient selon la configuration des volumes. Cette page explique la facturation des volumes clonés, des destinations SnapMirror, des LUN, des volumes temporaires et des volumes système. 
---
= Facturation Keystone pour des types de volumes spécifiques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les règles de facturation de Keystone varient selon certaines configurations de volumes. Connaître ces exceptions vous aide à éviter des frais imprévus lors de l'utilisation de volumes clonés, de destinations SnapMirror, de LUN ou de stockage temporaire.

Le tableau suivant récapitule les règles de facturation pour chaque type de volume.

[cols="1,2"]
|===
| Type de volume | Règle de facturation 


| Volumes clonés | Facturés comme volumes standard 


| Volumes temporaires | Non facturé 


| Destinations SnapMirror | Facturé au niveau de service de performance de destination 


| LUN | Facturé au niveau de service de performance du volume contenant 


| Volumes racine et système | Suivi mais non facturé 
|===


[[billing-for-cloned-volumes]]
== Facturation des volumes clonés

Les volumes clonés sont facturés comme des volumes standards au même niveau de service de performance que le volume à partir duquel ils ont été clonés. Tous les volumes clonés sont mesurés et facturés, quelle que soit leur taille ou leur finalité.



[[billing-for-temporary-volumes]]
== Facturation des volumes temporaires

Il arrive que des volumes temporaires soient créés par ONTAP lors du déplacement de volumes. Ces volumes temporaires sont de courte durée, et la consommation sur ces volumes n'est pas mesurée pour la facturation.



[[billing-for-snapmirror-destinations]]
== Facturation des destinations SnapMirror

La tarification des volumes de destination SnapMirror, qu'ils soient utilisés pour la reprise après sinistre ou la conservation à long terme, est basée sur le niveau de service de performance attribué à la destination. Aucun frais supplémentaire n'est appliqué pour la protection des données.



[[billing-for-luns]]
== Facturation des LUN

Pour les LUN, la facturation est basée sur les niveaux de service de performance du volume.



[[system-and-root-volumes]]
== Volumes racine et système

Les volumes système et racine sont surveillés dans le cadre du contrôle global du service Keystone, mais ne sont pas comptabilisés ou facturés. La consommation sur ces volumes est exemptée de la facturation.
