---
sidebar: sidebar 
permalink: concepts/misc-volume-billing-v2.html 
keywords: Billing and miscellaneous scenarios 
summary: Découvrez la facturation Keystone pour des configurations spécifiques, notamment les volumes clonés, la protection avancée des données et bien plus encore. 
---
= Scénarios divers pour la facturation Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprendre la facturation Keystone pour des configurations spécifiques de la version 2 (v2) peut vous aider à optimiser l'utilisation des services et à gérer les coûts. Ces configurations incluent les volumes clonés, la protection avancée des données, les volumes temporaires, les politiques de qualité de service (QoS), les destinations SnapMirror, les LUN et les volumes système/racine.



== Facturation des volumes clonés

Si les volumes sont clonés dans ONTAP et que vous les utilisez pour la sauvegarde et la restauration de vos données, vous pouvez continuer à utiliser ces clones sans paiements supplémentaires. Toutefois, les volumes clonés utilisés à d'autres fins dans votre entreprise pendant une durée étendue sont facturés.

Notez ce qui suit :

* Les volumes clones sont libres de se charger tant que leur taille est inférieure à 10 % du volume parent (capacité physique utilisée dans le volume clone par rapport à la capacité physique utilisée dans le volume parent).
* Il n'existe pas de délai de grâce de 24 heures pour les volumes clonés. Seule la taille du clone est prise en compte.
* Une fois que le volume clone dépasse 10 % de la taille physique du parent, le clone est facturé comme volume standard (capacité logique utilisée).




== Facturation pour la protection avancée des données

La protection avancée des données exploite NetApp MetroCluster pour mettre en miroir les données entre deux clusters séparés physiquement. Pour les agrégats MetroCluster en miroir, les données sont écrites deux fois, une fois sur chaque cluster. Le service Keystone facture la consommation de chaque côté de manière indépendante, ce qui engendre deux enregistrements de consommation identiques. Les frais d'extension sont appliqués à toutes les capacités de l'abonnement, que les données soient à la source ou qu'elles soient mises en miroir ou non.

Si vous surveillez les clusters via ONTAP System Manager (System Manager) ou Active IQ Unified Manager (Unified Manager), vous risquez de ne pas concorder avec le taux de consommation signalé sur ces outils et sur Keystone. System Manager et Unified Manager ne signalent pas les volumes sur le cluster (distant) en miroir, et ce faisant, indiquent la moitié des metrics de consommation que le service Keystone fournit.

.Exemple :
Les sites A et B sont configurés dans une configuration MetroCluster. Lorsqu'un utilisateur crée un volume de 10 To sur le site A, un volume identique de 10 To est créé sur le site B. Keystone identifie les 10 To de consommation sur chaque site pour une augmentation totale de 20 To. System Manager et Unified Manager signalent un volume de 10 To créé sur le site A, mais ne signalent pas un volume de 10 To sur le site B.

En outre, tous les volumes créés sur un système Keystone avec protection avancée des données sont pris en compte dans la consommation de la protection avancée des données, que ces volumes soient ou non mis en miroir.



== Facturation des volumes temporaires

Il arrive que des volumes temporaires soient créés par ONTAP lors du déplacement de volumes. Ces volumes temporaires sont de courte durée, et la consommation sur ces volumes n'est pas mesurée pour la facturation.



== Facturation et règles de QoS adaptatives

Keystone mesure la consommation en fonction des niveaux de service. Chaque niveau de service est associé à une règle de qualité de service (QoS) adaptative spécifique. Au cours du déploiement, vous serez informé des détails de chaque règle de QoS adaptative pour les services Keystone auxquels vous avez souscrit. Lors des opérations de gestion du stockage, assurez-vous que vos volumes disposent des règles de QoS adaptatives appropriées attribuées selon les niveaux de service souscrits pour éviter toute facturation inattendue. Pour plus d'informations sur les règles de QoS adaptative dans ONTAP, reportez-vous à link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Débit garanti avec les QoS"^]la section .



== Facturation des destinations SnapMirror

Les tarifs du volume de destination SnapMirror sont régis par la politique de QoS adaptative pour le niveau de services attribué à la source. Toutefois, si la source ne dispose pas d'une règle de QoS adaptative associée, la destination est facturée en fonction du niveau de service le plus bas disponible.



== Facturation des LUN

Pour les LUN, le même modèle de facturation est suivi que pour les volumes régis par des règles de QoS adaptatives. Si des règles de QoS adaptative distinctes sont définies sur les LUN, alors :

* La taille de la LUN est comptabilisée pour consommation en fonction du niveau de service associé à cette LUN.
* Le reste de l'espace du volume, le cas échéant, est facturé conformément à la règle de QoS adaptative du niveau de services défini sur le volume.




== Volumes racine et système

Les volumes système et racine sont surveillés dans le cadre du contrôle global du service Keystone, mais ne sont pas comptabilisés ou facturés. La consommation sur ces volumes est exemptée de la facturation.
