---
sidebar: sidebar 
permalink: concepts/nrnvc.html 
keywords: Non-returnable, non-volatile components, SnapLock compliance, add-on service 
summary: Composants non retournables et non volatiles et conformité au SnapLock 
---
= Composants non retournables et non volatiles et conformité au SnapLock
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans le cadre de votre abonnement NetApp Keystone, NetApp étend l'offre de composants non volatiles non renvoyables (NVC) pour vos services de fichiers, de blocs et d'objet.

Vous pouvez vous abonner à ce service complémentaire dans le cadre de votre abonnement Keystone.
Pour plus d'informations sur les services standard et cloud, consultez link:supported-storage-services.html["Services STaaS Keystone"].

Pour plus d'informations sur les niveaux de service, reportez-vous à la section link:../concepts/service-levels.html["Niveaux de service dans Keystone"].

NetApp ne restaure pas le support de stockage physique utilisé pendant toute la durée du service ou à la fin du service lorsque NetApp récupère l'ensemble de ses ressources physiques utilisées pour la réalisation du service.

Si vous avez acheté ce service, notez ce qui suit :

* Il n'est pas nécessaire de renvoyer les disques et la mémoire non volatile à la fin de la période de service, ou s'ils sont défectueux ou s'ils ont été détectés comme défectueux pendant la période de service.
* Toutefois, vous devez produire un certificat de destruction pour les disques et/ou la mémoire non volatile et ne peut pas être utilisé à d'autres fins.
* Le coût supplémentaire associé à la NRNVC est facturé en pourcentage du service d'abonnement total (inclut le service standard, la protection avancée des données et le Tiering des données).
* Ce service s'applique uniquement aux services de fichiers, de blocs et d'objets.




== Conformité aux normes SnapLock

La technologie SnapLock active la fonction NRNVC en rendant le disque inutilisable après la date d'expiration définie dans le volume. Pour utiliser la technologie SnapLock sur vos volumes, vous devez vous abonner à NRNVC. Ceci s'applique uniquement aux services de fichiers et de blocs.

Pour plus d'informations sur la technologie SnapLock, reportez-vous à la section https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html["Qu'est-ce que SnapLock"].
