---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: 'Keystone propose un modèle de paiement à l"utilisation pour répondre à vos besoins de consommation flexible et évolutif.' 
---
= Tarification Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous préférez un modèle de consommation OpEx plutôt que CapEx ou leasing, vous pouvez opter pour le modèle de paiement en tant que service NetApp Keystone qui assure une consommation flexible et évolutive avec des tarifs prévisibles et initiaux pour votre abonnement de stockage.

Keystone vous fournit les fonctionnalités de facturation suivantes :

* Vous pouvez payer en fonction des IOPS et de la capacité qui est dédiée à la latence pour répondre aux différents besoins des charges de travail. Les différents tiers de service de performance : Extreme, Premium, Performance, Standard, Value Et objet vous permettent de gérer le stockage en fonction du niveau de service que vous avez acheté.
* Il présente une facturation prévisible de la capacité engagée et du paiement à l'utilisation pour l'utilisation variable (en rafale).
* Vous pouvez sélectionner un prix de bundle pour le matériel, le système d'exploitation de base et le support pour un prix unitaire. Vous disposez d'une seule facture pour chaque type de stockage, service de fichier, bloc, objet ou service de stockage cloud.
* Sélectionnez une durée flexible pour les services et le paiement : vous pouvez choisir entre 12 mois, 25 Tio ou plus par site. Par la suite, vous pouvez procéder au renouvellement automatique pendant 12 mois.


La facturation de Keystone repose sur la capacité engagement et sur la consommation en rafale variable.

Pour plus d'informations sur les différentes capacités prises en charge par Keystone, reportez-vous à link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"].

*Informations connexes*

* link:../concepts/committed-capacity-billing.html["Facturation en fonction de la capacité engagement"]
* link:../concepts/consumed-capacity-billing.html["Mesure basée sur la capacité consommée"]
* link:../concepts/burst-consumption-billing.html["Facturation en fonction de la consommation en rafale"]
* link:../concepts/misc-volume-billing.html["Facturation en fonction des divers types de volume"]
* link:../concepts/billing-schedules.html["Calendriers de facturation"]

