---
sidebar: sidebar 
permalink: concepts/pricing-v2.html 
keywords: pricing, billing introduction, Keystone billing 
summary: 'Keystone propose un modèle de paiement à l"utilisation pour répondre à vos besoins de consommation flexible et évolutif.' 
---
= Tarification Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service d'abonnement à la carte NetApp Keystone STaaS offre une consommation flexible et évolutive avec une tarification prévisible et à l'avance pour vos besoins de stockage.

Keystone pour la version 2 (v2) vous offre les fonctionnalités de facturation suivantes :

* Vous pouvez payer en fonction des IOPS et de la capacité qui est dédiée à la latence pour répondre aux différents besoins des charges de travail. Les différents tiers de service de performance : Extreme, Premium, Performance, Standard, Value Et objet vous permettent de gérer le stockage en fonction du niveau de service que vous avez acheté.
* Il présente une facturation prévisible de la capacité engagée et du paiement à l'utilisation pour l'utilisation variable (en rafale).
* Vous pouvez sélectionner un prix de bundle pour le matériel, le système d'exploitation de base et le support pour un prix unitaire. Vous disposez d'une seule facture pour chaque type de stockage, service de fichier, bloc, objet ou service de stockage cloud.
* Vous pouvez sélectionner une durée flexible pour les services et les options de paiement, telles que mensuellement, trimestriellement ou annuellement.


La facturation de Keystone repose sur la capacité engagement et sur la consommation en rafale variable.

Pour plus d'informations sur les différentes capacités prises en charge par Keystone, reportez-vous à link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"].

*Informations connexes*

* link:../concepts/committed-capacity-billing-v2.html["Facturation en fonction de la capacité engagement"]
* link:../concepts/consumed-capacity-billing-v2.html["Mesure basée sur la capacité consommée"]
* link:../concepts/burst-consumption-billing-v2.html["Facturation en fonction de la consommation en rafale"]
* link:../concepts/misc-volume-billing-v2.html["Facturation en fonction des divers types de volume"]
* link:../concepts/billing-schedules-v2.html["Calendriers de facturation"]

