---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Qualité de service dans Keystone 
---
= Qualité de service (QoS) dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La qualité de service (QoS) du stockage est une technologie stratégique qui permet aux applications d'obtenir des performances cohérentes et prévisibles. Sans la QoS, certaines charges de travail, comme le démarrage de plusieurs systèmes, peuvent allouer des ressources entières pendant un certain temps et affecter d'autres charges de travail. Pour plus d'informations sur la QoS, reportez-vous à la section https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Débit garanti avec les QoS"^].

La QoS garantit que les applications bénéficient à tout moment de performances prévisibles. NetApp ONTAP définit deux paramètres pour la QoS : les plafonds- https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-ceilings-qos-max["QoS max"^], et débit sol- https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-floors-qos-min["QoS min"^]. QoS Max représente le nombre maximal d'IOPS ou de Mbit/s ou IOPS et Mbit/s que peut atteindre un workload. Par contre, QoS min garantit que le débit d'une charge de travail n'est pas inférieur à un certain nombre d'IOPS ou de Mbit/s, ou IOPS et Mbit/s.



== La QoS adaptative

La QoS adaptative (AQoS) est utilisée pour les services Keystone afin de maintenir le rapport entre les IOPS et les To/Go lorsque la taille modifie la règle de QoS est automatiquement appliquée. Pour plus d'informations sur la QoS adaptative, reportez-vous à la section https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["À propos de la QoS adaptative"^].

Keystone vous fournit des règles de QoS adaptatives que vous pouvez configurer une fois votre cluster en production. Vous devez vous assurer que tous vos volumes sont associés aux règles de QoS adaptatives créées et disponibles dans votre système.


NOTE: Si vous n'avez pas appliqué correctement des règles de qualité de service adaptatives sur vos volumes, ces volumes seront mesurés et facturés au niveau de service le plus élevé conformément à votre abonnement. Cela peut entraîner des frais d'éclatement intempestive.



== Configuration du groupe de règles de QoS adaptative

Vous pouvez configurer des règles de QoS adaptative pour adapter automatiquement une taille maximale ou maximale du volume à une taille maximale. Pour configurer une stratégie, vous devez connaître les éléments suivants :

* *Nom du groupe de règles* : le nom du groupe de règles de qualité de service adaptative. Par exemple : `Keystone_extreme`.
* *VServer* : nom de la machine virtuelle de stockage ou VServer (machine virtuelle de stockage).
* *IOPS attendues* : le nombre d'IOPS/Tio ONTAP fournit au moins tant que la performance est garantie.
* *Peak IOPS* : le nombre maximal d'IOPS/Tio qui sera disponible pour un volume avant que les performances ne soient limitées.
* *Allocation d'IOPS prévue* : ce champ contrôle si les IOPS disponibles attendues pour le volume sont basées sur la taille allouée ou utilisée du volume. Dans Keystone, il s'agit de la base de l'espace alloué.
* *Affectation des IOPS de pointe* : ce champ contrôle si les IOPS de pointe disponibles pour le volume sont basées sur la taille allouée ou utilisée du volume. Dans Keystone, il s'agit de l'espace utilisé.
* *IOPS minimum absolu* : le nombre le plus faible d'IOPS attendu qui sera appliqué à un volume si sa taille est très petite, ce qui se traduit par un nombre inacceptable d'IOPS. Cette valeur est par défaut de 1,000 pour `Extreme`, 500 pour `Premium`, et 75 pour les autres niveaux de service.
+

NOTE: Il ne s'agit pas de la densité des IOPS (par exemple 75 IOPS/Tio), mais d'un nombre minimal absolu d'IOPS.



Pour plus d'informations sur la densité des E/S, voir link:../concepts/metrics.html["Mesures et définitions utilisées dans les services Keystone"]. Pour plus d'informations sur les groupes de stratégies AQoS, voir https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["Utilisez les groupes de règles de QoS adaptatifs"^].



== Paramètres des règles de QoS adaptative

Les paramètres des règles de QoS adaptative pour chaque niveau de service sont décrits dans les sections suivantes. Les tailles minimale et maximale des volumes pour chaque niveau de service fournies ici permettent d'optimiser les valeurs d'IOPS et de latence pour un volume. La création de trop de volumes en dehors de ces instructions peut nuire aux performances de ces volumes.



=== Des paramètres pour le niveau de service extrême

Paramètres et commandes du niveau de service Extreme :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 1000
....
* Taille minimale du volume : 100 Gio, 0,Tio
* Taille maximale du volume : 10 Tio




=== Paramètres du niveau de service Premium

Paramètres et commandes du niveau de service Premium :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 500
....
* Taille minimale du volume : 500 Gio, 0,5 Tio
* Taille maximale du volume : 50 Tio




=== Paramètres du niveau de service Performance

Paramètres et commandes du niveau de service Performance :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 250
....
* Taille minimale du volume : 500 Gio, 0,5 Tio
* Taille maximale du volume : 80 Tio




=== Paramètres du niveau de service Standard

Paramètres et commandes du niveau de service Standard :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 77
....
* Taille minimale du volume : Tio
* Taille maximale du volume : 100 Tio




=== Paramètres du niveau de service valeur

Paramètres et commandes du niveau de service de valeur :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 59
....
* Taille minimale du volume : Tio
* Taille maximale du volume : 100 Tio




== Calcul de la taille de bloc

Notez ces points avant de calculer la taille du bloc à l'aide des paramètres suivants :

* IOPS/Tio = Mbit/s/Tio divisé par (taille de bloc * 1024)
* La taille de bloc est en Ko/E/S.
* Tio = 1024 Gio ; Gio = 1024MiB ; MIB = 1024Kio ; Kio = 1024 octets ; par base 2
* TB = 1000 Go ; GB = 1000 Mo ; MB = 1000 Ko ; KB = 1000 octets ; par base 10


.Calcul de la taille du bloc d'échantillons
Pour calculer le débit du niveau de service a, par exemple le niveau de service «Extreme» :

* IOPS à maximum : 12,288
* Taille de bloc par E/S : 32 Ko
* Débit maximum = (12288 * 32 * 1024) / (1024*1024) = 384 Mbit/s.


Si un volume possède 700 Gio de données logiques utilisées, le débit disponible est :

`débit maximum = 384 * 0.7 = 268,8 MBps`
