---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone utilise la QoS du stockage pour assurer des performances cohérentes et prévisibles aux applications. 
---
= QoS du stockage dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone utilise la qualité de service (QoS) du stockage pour assurer des performances cohérentes et prévisibles aux applications. Sans la QoS, certaines charges de travail, telles que celles pour le démarrage de plusieurs systèmes, peuvent consommer la plupart, voire la totalité, des ressources pendant une période donnée et affecter d'autres charges de travail.

Pour plus d'informations sur QoS, voir https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Débit garanti avec les QoS"^].



== La QoS adaptative

La QoS adaptative (AQoS) est utilisée par les services Keystone pour maintenir dynamiquement le ratio IOPS/Tio en fonction de la taille du volume. Pour plus d'informations sur les stratégies AQoS, voir https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["À propos de la QoS adaptative"^].

Keystone vous fournit des règles AQoS que vous pouvez configurer une fois que votre cluster est en production. Vous devez vous assurer que tous vos volumes sont associés aux règles AQoS correctes qui sont déjà créées et disponibles dans votre système.

Un volume ONTAP n'est pas conforme s'il n'a pas de politique AQoS appliquée. Un volume sans politique QoS est la dernière dans la liste de priorité pour que le système puisse réaliser des opérations d'entrée/sortie. Cependant, si des opérations d'entrée-sortie sont disponibles, le volume pourrait consommer toutes les E/S disponibles.


NOTE: Si vous n'avez pas appliqué de règles AQoS à vos volumes, ces volumes seront mesurés et facturés au niveau de service le plus élevé, conformément à votre abonnement. Cela peut entraîner des frais d'éclatement intempestive.



== Paramètres de QoS adaptative

Les paramètres de QoS adaptative (AQoS) varient en fonction des niveaux de service.

|===


| *Nom de la politique* | *Extrême* | *Premium* | *Performance* | *Standard* | *Valeur* 


| *IOPS/Tio attendu* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Allocation d'IOPS attendue* 5+| Espace alloué 


| *Pic IOPS/Tio* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Allocation maximale d'IOPS* 5+| Espace utilisé 


| *Taille de bloc* 5+| 32 KO 
|===


== Configuration du groupe de règles de QoS adaptative

Vous pouvez configurer des règles de QoS adaptative (AQoS) pour faire évoluer automatiquement un plafond de débit ou un volume au sol en fonction de sa taille. Tous les niveaux de service de Keystone ne sont pas alignés sur les règles de QoS ONTAP par défaut. Vous pouvez créer des règles de QoS personnalisées pour ces règles. Pour configurer une stratégie, vous devez connaître les éléments suivants :

* *Nom du groupe de règles* : le nom du groupe de stratégies AQoS. Par exemple : `Keystone_extreme`.
* *VServer* : nom de la machine virtuelle de stockage ou VServer (machine virtuelle de stockage).
* *IOPS/Tio attendu* : nombre minimal d'IOPS par Tio allouée par volume que le système tente de fournir lorsque suffisamment d'IOPS système sont disponibles.
* *Pic IOPS/Tio* : nombre maximal d'IOPS par Tio utilisé par volume que le système autorise le volume à atteindre avant qu'il n'accélère les IOPS par injection de latence.
* *Allocation d'IOPS attendue* : ce paramètre détermine si les IOPS attendues disponibles pour le volume sont basées sur la taille allouée ou utilisée du volume. Dans Keystone, il s'agit de la base de l'espace alloué.
* *Allocation d'IOPS de pic* : ce paramètre détermine si les IOPS de pic disponibles pour le volume sont basées sur la taille allouée ou utilisée du volume. Dans Keystone, il s'agit de l'espace utilisé.
* *IOPS minimum absolu* : le nombre le plus faible d'IOPS attendu qui sera appliqué à un volume si sa taille est très petite, ce qui se traduit par un nombre inacceptable d'IOPS. Cette valeur est par défaut de 1,000 pour `Extreme`, 500 pour `Premium`, et 250 pour `Performance`, et 75 pour `Standard` et `Value` niveaux de services
+

NOTE: Il ne s'agit pas de la densité des IOPS (par exemple 75 IOPS/Tio), mais d'un nombre minimal absolu d'IOPS.



Pour plus d'informations sur la densité des E/S, voir link:../concepts/metrics.html["Mesures et définitions utilisées dans les services Keystone"]. Pour plus d'informations sur les groupes de stratégies AQoS, voir https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["Utilisez les groupes de règles de QoS adaptatifs"^].



== Paramètres des règles de QoS adaptative

Les paramètres des règles de QoS adaptative (AQoS) pour chaque niveau de service sont décrits dans les sections suivantes. Les tailles minimale et maximale des volumes pour chaque niveau de service fournies ici permettent d'optimiser les valeurs d'IOPS et de latence pour un volume. La création de trop de volumes en dehors de ces instructions peut nuire aux performances de ces volumes.



=== Des paramètres pour le niveau de service extrême

Paramètres et commandes du niveau de service Extreme :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* Taille minimale du volume : 100 Gio, 0,Tio
* Taille maximale du volume : 10 Tio




=== Paramètres du niveau de service Premium

Paramètres et commandes du niveau de service Premium :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* Taille minimale du volume : 500 Gio, 0,5 Tio
* Taille maximale du volume : 50 Tio




=== Paramètres du niveau de service Performance

Paramètres et commandes du niveau de service Performance :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* Taille minimale du volume : 500 Gio, 0,5 Tio
* Taille maximale du volume : 80 Tio




=== Paramètres du niveau de service Standard

Paramètres et commandes du niveau de service Standard :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Taille minimale du volume : Tio
* Taille maximale du volume : 100 Tio




=== Paramètres du niveau de service valeur

Paramètres et commandes du niveau de service de valeur :

* Exemple de commande :


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Taille minimale du volume : Tio
* Taille maximale du volume : 100 Tio




== Calcul de la taille de bloc

Notez ces points avant de calculer la taille du bloc à l'aide des paramètres suivants :

* IOPS/Tio = Mbit/s/Tio divisé par (taille de bloc * 1024)
* La taille de bloc est en Ko/E/S.
* Tio = 1024 Gio ; Gio = 1024MiB ; MIB = 1024Kio ; Kio = 1024 octets ; par base 2
* TB = 1000 Go ; GB = 1000 Mo ; MB = 1000 Ko ; KB = 1000 octets ; par base 10


.Calcul de la taille du bloc d'échantillons
Pour calculer le débit d'un niveau de service, par exemple `Extreme` niveau de services :

* IOPS à maximum : 12,288
* Taille de bloc par E/S : 32 Ko
* Débit maximum = (12288 * 32 * 1024) / (1024*1024) = 384 Mbit/s.


Si un volume possède 700 Gio de données logiques utilisées, le débit disponible est :

`débit maximum = 384 * 0.7 = 268,8 MBps`
