---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS pour la version 3 offre une capacité de stockage à des niveaux de service prédéfinis. Chaque volume géré par Keystone est associé à un niveau de service. 
---
= Niveaux de service de performance dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS pour la version 3 (v3) offre une capacité de stockage de données à des niveaux de service de performances prédéfinis. Chaque volume géré par les services Keystone est associé à un niveau de service de performance.

Un abonnement peut comporter plusieurs forfaits, chacun correspondant à un niveau de service de performance. Chaque forfait dispose d'une capacité garantie par niveau de service de performance.

Un niveau de service de performance peut comporter plusieurs instances, chacune représentant une baie de stockage distincte affectée à ce niveau de service dans l'environnement du client. Chaque niveau de service de performance est défini par le nombre d'opérations d'entrée/sortie par seconde (IOPS), le débit (Gbps) et la latence (ms), ces mesures étant mesurées et appliquées par instance de niveau de service de performance.

Vous sélectionnez les niveaux de service de performances en fonction de votre environnement de stockage et de vos besoins de stockage et de consommation. Les niveaux de service de performances de base sont disponibles pour vous par défaut. Des niveaux de service de performance spécifiques sont également disponibles, si vous avez opté pour des services complémentaires.


TIP: Une description détaillée du service pour les niveaux de service de performance NetApp Keystone STaaS est disponible  https://www.netapp.com/services/keystone/terms-and-conditions/["ici"^] .

Les niveaux de service de performances de base pour les types de stockage pris en charge, les services unifiés, optimisés par blocs, d'objets et cloud sont décrits dans les sections suivantes :



== Niveaux de service de performance pour le stockage unifié

*Protocoles pris en charge* : FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===


| *Niveau de service de performance* (toutes les spécifications par instance de niveau de service de performance) | *Extrême* | *Premium* | *Standard* | *Valeur* 


| *Exemples de types de charge de travail* | IA/ML, HPC, base de données InMem | Analytique, EDA, OLTP | OLAP, IoT, conteneurs | Sauvegarde, archivage 


| *IOPS maximum*^1^ | 1M | 550 000 | 500 000 | NA 


| *Gbps maximum* | 40 | 20 | 20 | NA 


| *Cible 90^TH^ latence percentile* | <=1 ms | <=1 ms | <=4 ms | > 4 ms 


| *Capacité minimale engagée* | 50 Tio | 50 Tio | 100 Tio | 100 Tio 


| *Augmentation progressive de la capacité engagée* 4+| 25TiB 


| *Type de capacité engagée et mesurée* 4+| Logique ou physique 
|===


== Niveaux de service de performance pour le stockage optimisé par blocs

*Protocoles pris en charge* : NVMe/TCP, NVMe/FC, FC, iSCSI

|===


| *Niveau de service de performance* (toutes les spécifications par instance de niveau de service de performance) | *Extrême* | *Premium* 


| *Exemples de types de charge de travail* 2+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *IOPS maximum*^1^ | 850 000 | 450 000 


| *Gbps maximum* | 65 | 25 


| *Cible 90^TH^ latence percentile* | <=1 ms | <=1 ms 


| *Capacité minimale engagée* | 50 Tio | 50 Tio 


| *Augmentation progressive de la capacité engagée* 2+| 25TiB 


| *Type de capacité engagée et mesurée* 2+| Logique ou physique 
|===

NOTE: ^1^Objectifs mutuellement exclusifs. Les performances réelles peuvent varier en fonction de divers facteurs, notamment la version du système d'exploitation, le matériel, le type de charge de travail et le nombre d'opérations simultanées.



=== En savoir plus sur les niveaux de service de performance pour le stockage unifié et optimisé par blocs

Les mesures de niveau de service de performance de base dépendent des conditions suivantes :

* Les niveaux de service de performances prennent en charge ONTAP 9.8 et versions ultérieures.
* Pour un stockage unifié,
+
** *IOPS* : pour ONTAP 9.16.1 avec NFS, chaque instance de niveau de performance prend en charge l'accès aléatoire avec un rapport de lecture de 70 % et d'écriture de 30 %, une taille de bloc de 8 Ko et une latence de 1 ms (4 ms pour Standard).
** *Débit* : Pour ONTAP 9.16.1 avec NFS, chaque instance de niveau de performance prend en charge l'accès séquentiel avec 100 % de lecture et une taille de bloc de 32 Ko.


* Pour un stockage optimisé par blocs,
+
** *IOPS* : pour ONTAP 9.16.1 avec FCP, chaque instance de niveau de performance prend en charge l'accès aléatoire avec un rapport de lecture de 70 % et d'écriture de 30 %, une taille de bloc de 8 Ko et une latence de 1 ms.
** *Débit* : Pour ONTAP 9.16.1 avec FCP, chaque instance de niveau de performance prend en charge l'accès séquentiel avec 100 % de lecture et une taille de bloc de 64 Ko.


* La latence n'inclut pas les éléments suivants :
+
** latence de l'hôte ou de l'application
** latence du réseau du client vers ou depuis les ports du contrôleur
** Frais généraux associés au transfert des données vers le magasin d'objets en cas de FabricPool


* Les valeurs de latence ne s'appliquent pas aux opérations d'écriture MetroCluster. Ces opérations d'écriture dépendent de la distance entre les systèmes distants.
* La règle _IOPS attendues_ est destinée à FabricPool uniquement si la règle de Tiering est définie sur « aucun » et qu'aucun bloc n'est dans le cloud. _IOPS attendues_ est destiné aux volumes qui ne font pas partie d'une relation synchrone SnapMirror.




== Niveaux de service de performance pour le stockage d'objets

*Protocole pris en charge* : S3

|===


| *Niveau de service de performance* | *Standard* | *Valeur* 


| *Capacité minimale engagée par commande* | 200 Tio | 500 Tio 


| *Augmentation progressive de la capacité engagée* | 25 Tio | 100 Tio 


| *Type de capacité engagée et mesurée* 2+| Physique 
|===


== Le stockage cloud

*Protocoles pris en charge* : NFS, CIFS, iSCSI et S3 (AWS et Azure uniquement)

|===


| *Niveau de service de performance* | Cloud Volumes ONTAP 


| *Capacité minimale engagée par commande* | 4 Tio 


| *Augmentation progressive de la capacité engagée* | 1 Tio 


| *Type de capacité engagée et mesurée* | Logique 
|===
[NOTE]
====
* Les services cloud natifs, tels que le calcul, le stockage et la mise en réseau, sont facturés par les fournisseurs cloud.
* Ces services dépendent de caractéristiques de stockage et de calcul cloud.


====
*Informations connexes*

* link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge"]
* link:..//concepts/metrics.html["Mesures et définitions utilisées dans les services Keystone"]
* link:../concepts/pricing.html["Tarification Keystone"]

