---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level 
summary: Niveaux de service pris en charge 
---
= Niveaux de service dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service Keystone STaaS offre la capacité de stockage des données avec des niveaux de service (niveaux de service) prédéfinis sur la base d'un abonnement.

Les niveaux de service sont définis selon :

* Latence moyenne
* IOPS maximales par To logiques stocké par volume


Un volume doit être associé à un niveau de service.



== Niveaux de service pour le stockage pris en charge

Les niveaux de service pour les services fichier, bloc, objet et cloud sont répertoriés ici.



=== Stockage basé sur des fichiers et des blocs

*Protocoles pris en charge* : NFS, CIFS, iSCSI et FC

|===


| *Niveau de service* | *Extrême* | *Premium* | *Performance* | *Standard* | *Valeur* 


| *Exemples de types de charge de travail* | Analyses, bases de données, applications stratégiques | VDI, VSI, développement logiciel | OLTP, OLAP, conteneurs, développement logiciel | Partages de fichiers, serveurs web | Sauvegarde 


| *Nombre maximal d'IOPS/tibides logiques stockés par volume* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Nombre maximum de Mbit/s/tibides logiques stockés par volume* | 384 | 128 | 64 | 16 | 4 


| * Latence* | <1 ms | <2 ms | <4 ms | <17 ms | <17 ms 
|===

NOTE: Notez les points suivants pour les mesures de performances de débit (uniquement applicables aux services de niveau bloc et fichier) :

* Les niveaux de service de fichiers et de blocs sont basés sur ONTAP 9.7 et versions ultérieures.
* Les valeurs des IOPS/Tio et de latence pour les niveaux de service sont basées sur la quantité de données logiques stockées dans le volume, sur la taille de bloc de 32 Ko et sur une combinaison aléatoire de 70 % de lectures et de 30 % d'E/S en écriture.
* Les IOPS/Tio et/ou Mbit/s/Tio réels varient en fonction des modèles d'utilisation et de la simultanéité des charges de travail.
* La latence n'inclut pas les éléments suivants :
+
** Les applications, les hôtes ou les temps de latence du réseau du client vers ou depuis les ports du contrôleur.
** Latence automatiquement appliquée par QoS pour maintenir les E/S dans les limites maximales de niveau de service.


* Lorsque vous utilisez le service d'extension Advanced Data protection, la latence cible s'applique uniquement au traitement des demandes d'E/S des produits Keystone locaux.




=== Stockage objet

*Protocole pris en charge* : S3

|===


| *Niveau de service* | Objet 


| *Type de charge de travail* | Référentiel multimédia, archivage 


| *Nombre maximal d'IOPS/Tio logique stockée par volume* | S/O 


| *Nombre maximum de Mbit/s/Tio logique stockée par volume* | S/O 


| * Latence moyenne* | S/O 
|===

NOTE: La latence n'inclut pas les surcharges associées au transfert de données vers le magasin d'objets en cas de stockage FabricPool.



=== Le stockage cloud

*Protocole pris en charge* : NFS, CIFS, iSCSI et S3 (AWS et Azure uniquement)

|===


| *Niveau de service* | Cloud Volumes ONTAP® 


| *Type de charge de travail* | Reprise après incident, développement/test de logiciels, applications d'entreprise 


| *Nombre maximal d'IOPS/Tio logique stockée par volume* | S/O 


| *Nombre maximum de Mbit/s/Tio logique stockée par volume* | S/O 


| * Latence moyenne* | S/O 
|===

NOTE: Remarque :

* Les services cloud natifs, tels que le calcul, le stockage et le réseau, sont facturés par les fournisseurs cloud.
* Ces services dépendent des caractéristiques de stockage et de calcul dans le cloud.

