---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Niveaux de service pris en charge 
---
= Niveaux de service dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service Keystone STaaS offre la capacité de stockage des données avec des niveaux de service (niveaux de service) prédéfinis sur la base d'un abonnement. Chaque volume géré par les services Keystone est associé à un niveau de service.

Un abonnement peut avoir plusieurs abonnements et chaque abonnement correspond à un niveau de service. Chaque plan tarifaire dispose d'une capacité engagée par niveau de service.

Chaque niveau de services est défini par sa densité d'E/S, à savoir IOPS/Tio/volume. Il s'agit du rapport entre les performances (opérations d'entrée/sortie par seconde [IOPS]) et la capacité de stockage utilisée (Tio), qui correspond au nombre d'IOPS/Tio à la latence moyenne par volume.

Les niveaux de service des types de stockage, des services fichier, bloc, objet et cloud pris en charge sont répertoriés ici.



== Niveaux de service pour le stockage fichier et bloc

*Protocoles pris en charge* : NFS, CIFS, iSCSI et FC

|===


| *Niveau de service* | *Extrême* | *Premium* | *Performance* | *Standard* | *Valeur* 


| *Exemples de types de charge de travail* | Analyses, bases de données, applications stratégiques | VDI, VSI, développement logiciel | OLTP, OLAP, conteneurs, développement logiciel | Partages de fichiers, serveurs web | Sauvegarde 


| *Nombre maximal d'IOPS/tibides logiques stockés par volume* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Nombre maximal d'IOPS/de Tibs logiques alloués par volume* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Nombre maximum de Mbit/s/Tibs logiques stockés par volume à 32 K B/S* | 384 | 128 | 64 | 16 | 4 


| * Latence moyenne* | 1 ms. | 2 ms. | 4 ms. | 17 ms. | 17 ms. 


| *Taille de bloc* 5+| 32 KO 
|===


=== En savoir plus sur les niveaux de service pour le stockage fichier et bloc

Les indicateurs de niveau de service dépendent des conditions suivantes :

* Les niveaux de service pour le stockage fichier et bloc prennent en charge ONTAP 9.7 et versions ultérieures.
* Les valeurs d'IOPS/Tio/volume, de Mo/sec/Tio/volume et de latence pour les niveaux de services sont basées sur la quantité de données stockées dans le volume, la taille de bloc de 32 Ko et une combinaison aléatoire d'opérations d'E/S de 70 % en lecture et 30 % en écriture.
* La quantité réelle d'IOPS/Tio/volume et de Mo/sec/Tio/volume peut varier en fonction de la taille de bloc réelle ou estimée, de la simultanéité des workloads du système ou des opérations d'entrée/sortie.
* La latence n'inclut pas les éléments suivants :
+
** latence de l'hôte ou de l'application
** latence du réseau du client vers ou depuis les ports du contrôleur
** Frais généraux associés au transfert des données vers le magasin d'objets en cas de FabricPool
** La latence est automatiquement appliquée par la QoS pour maintenir les E/S dans les limites des limites maximales du niveau de service


* Les valeurs de latence ne s'appliquent pas aux opérations d'écriture MetroCluster. Ces opérations d'écriture dépendent de la distance entre les systèmes distants.
* Si une règle AQoS n'est pas attribuée à un ou plusieurs volumes d'un système de stockage, ces volumes sont considérés comme des volumes non conformes et aucun niveau de service cible n'est applicable à ces systèmes.
* La règle _IOPS attendues_ est destinée à FabricPool uniquement si la règle de Tiering est définie sur « aucun » et qu'aucun bloc n'est dans le cloud. _IOPS attendues_ est destiné aux volumes qui ne font pas partie d'une relation synchrone SnapMirror.
* Les opérations d'E/S des workloads doivent être équilibrées sur tous les contrôleurs déployés, comme le détermine l'ordre Keystone.




== Stockage objet

*Protocole pris en charge* : S3

|===


| *Niveau de service* | Objet 


| *Type de charge de travail* | Référentiel multimédia, archivage 


| *Nombre maximal d'IOPS/Tio logique stockée par volume* | S/O 


| *Nombre maximum de Mbit/s/Tio logique stockée par volume* | S/O 


| * Latence moyenne* | S/O 
|===

NOTE: La latence n'inclut pas les surcharges associées au transfert de données vers le magasin d'objets en cas de stockage FabricPool.



== Le stockage cloud

*Protocole pris en charge* : NFS, CIFS, iSCSI et S3 (AWS et Azure uniquement)

|===


| *Niveau de service* | Cloud Volumes ONTAP® 


| *Type de charge de travail* | Reprise après incident, développement/test de logiciels, applications d'entreprise 


| *Nombre maximal d'IOPS/Tio logique stockée par volume* | S/O 


| *Nombre maximum de Mbit/s/Tio logique stockée par volume* | S/O 


| * Latence moyenne* | S/O 
|===
[NOTE]
====
* Les services cloud natifs, tels que le calcul, le stockage et le réseau, sont facturés par les fournisseurs cloud.
* Ces services dépendent des caractéristiques de stockage et de calcul dans le cloud.


====