---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS pour la version 3 offre une capacité de stockage à des niveaux de service prédéfinis. Chaque volume géré par Keystone est associé à un niveau de service. 
---
= Niveaux de service de performance dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS propose des niveaux de service de performance (PSL) prédéfinis, également appelés niveaux de service de performance de base, pour chaque type de stockage. Chaque PSL spécifie les objectifs de performance (IOPS, débit et latence), les protocoles pris en charge, la plateforme et les exigences minimales de capacité. Consultez les PSL disponibles pour sélectionner le niveau de service approprié à votre charge de travail et planifier votre abonnement.

Un abonnement Keystone peut inclure plusieurs PSL sur un ou plusieurs types de stockage. Chaque PSL a une capacité engagée, qui correspond à la capacité minimale facturée pour ce niveau de service pendant la durée de l’abonnement.


NOTE: Un abonnement AFX est limité au type de stockage AFX et ne propose actuellement qu'un seul PSL, Extreme.



[[performance-service-levels-instances]]
== instances de niveaux de service de performance

Un niveau de service de performance (PSL) peut comporter plusieurs instances, appelées instances de niveau de service de performance (PSLI), au sein de votre environnement. Chaque PSLI est un système de stockage distinct affecté à ce niveau de service de performance, avec une capacité engagée mesurée par PSLI.

* Pour le stockage unifié ou optimisé par blocs, un PSLI est une baie de stockage composée de deux contrôleurs de stockage dans une paire haute disponibilité avec des supports de stockage internes ou externes.
* Pour le stockage AFX, un PSLI correspond à un contrôleur de stockage AFX unique. AFX utilise une architecture désagrégée où les contrôleurs (compute) et les baies de disques (stockage) sont indépendants et peuvent être dimensionnés séparément. Les objectifs d'IOPS et de débit s'appliquent à chaque contrôleur ; la capacité engagée est mesurée au niveau du cluster AFX, qui inclut tous les contrôleurs et baies de disques du cluster.


Les indicateurs de performance tels que les IOPS, le débit (GBps) et la latence (ms) sont mesurés par PSLI.


TIP: Une description détaillée du service pour les niveaux de service de performance NetApp Keystone STaaS est disponible  https://www.netapp.com/services/keystone/terms-and-conditions/["ici"^] .

Les niveaux de service de performance de base pour les types de stockage des données pris en charge : unifié, optimisé pour le stockage bloc, AFX, objet et service cloud sont décrits dans les sections suivantes :



[[performance-service-levels-for-unified-storage]]
== Niveaux de service de performance pour le stockage unifié

|===


| *Niveau de service de performance* (toutes les spécifications par instance de niveau de service de performance [paire haute disponibilité]) | *Extrême* | *Premium* | *Standard* | *Valeur* 


| *Protocoles pris en charge* 4+| FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3 


| *Exemples de types de charge de travail* | IA/ML, HPC, base de données InMem | Analytique, EDA, OLTP | OLAP, IoT, conteneurs | Sauvegarde, archivage 


| *Cible 90^TH^ latence percentile* | <=1 ms | <=1 ms | <=4 ms | > 4 ms 


| *IOPS maximales cibles*^1^ | 1M | 550 000 | 250 K | NA 


| *Débit maximal cible en Go/s*^1^ | 40 | 20 | 10 | NA 


| *Plate-forme* | AFF série A | AFF série A | AFF C-Series | FAS 


| *Capacité minimale engagée* | 50 Tio | 50 Tio | 100 Tio | 100 Tio 


| *Augmentation progressive de la capacité engagée* 4+| 25 Tio 


| *Type de capacité engagée et mesurée* 4+| Logique ou physique 
|===


[[performance-service-levels-for-block-optimized-storage]]
== Niveaux de service de performance pour le stockage optimisé par blocs

|===


| *Niveau de service de performance* (toutes les spécifications par instance de niveau de service de performance [paire haute disponibilité]) | *Extrême* | *Premium* | *Standard* 


| *Protocoles pris en charge* 3+| NVMe/TCP, NVMe/FC, FC, iSCSI 


| *Exemples de types de charge de travail* 3+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *Cible 90^TH^ latence percentile* | <=1 ms | <=1 ms | <=4 ms 


| *IOPS maximales cibles*^1^ | 850 000 | 450 000 | 120K 


| *Débit cible maximal en Go/s* | 65 | 25 | 6 


| *Plate-forme* | ASA série A | ASA série A | ASA série C 


| *Capacité minimale engagée* | 50 Tio | 50 Tio | 100 Tio 


| *Augmentation progressive de la capacité engagée* 3+| 25TiB 


| *Type de capacité engagée et mesurée* 3+| Logique ou physique 
|===


[[performance-service-levels-for-afx-storage]]
== Niveaux de service de performance pour le stockage AFX

|===


| *Niveau de service de performance* (toutes les spécifications par instance de niveau de service de performance [un contrôleur de stockage AFX]) | *Extrême* 


| *Protocoles pris en charge* | NFSv3, NFSv4/RDMA, pNFS, SMB, S3 


| *Exemples de types de charge de travail* | IA/ML, HPC, base de données InMem 


| *Cible 90^TH^ latence percentile* | <=1 ms 


| *IOPS maximales cibles*^1^ | 625 K 


| *Débit cible maximal en Go/s* | 20 


| *Plate-forme* | AFX 


| *Capacité minimale engagée par cluster AFX*^2^ | 200 Tio 


| *Augmentation progressive de la capacité engagée* | 100 Tio 


| *Type de capacité engagée et mesurée* | Physique 
|===
[NOTE]
====
* ^1^Objectifs mutuellement exclusifs. Les performances réelles peuvent varier en fonction de divers facteurs, notamment la version du système d'exploitation, le matériel, le type de charge de travail et le nombre d'opérations simultanées.
* Dans un cluster AFX, les objectifs de performance s'appliquent par contrôleur de stockage. Chaque contrôleur ajouté au cluster contribue aux mêmes IOPS et au même débit. La capacité engagée et les augmentations incrémentales s'appliquent à la capacité totale des baies de disques du cluster.


====


[[performance-measurement-conditions-for-unified-block-optimized-and-afx-storage]]
== Conditions de mesure des performances pour le stockage unifié, optimisé par blocs et AFX

Les mesures de niveau de service de performance de base dépendent des conditions suivantes :

* Les niveaux de service de performances prennent en charge ONTAP 9.8 et versions ultérieures.
* Pour un stockage unifié,
+
** *IOPS* : pour ONTAP 9.16.1 avec NFS, chaque instance de niveau de performance prend en charge l'accès aléatoire avec un rapport de lecture de 70 % et d'écriture de 30 %, une taille de bloc de 8 Ko et une latence de 1 ms (4 ms pour Standard).
** *Débit* : Pour ONTAP 9.16.1 avec NFS, chaque instance de niveau de performance prend en charge l'accès séquentiel avec 100 % de lecture et une taille de bloc de 32 Ko.


* Pour un stockage optimisé par blocs,
+
** *IOPS* : pour ONTAP 9.16.1 avec FCP, chaque instance de niveau de performance prend en charge l'accès aléatoire avec un rapport de lecture de 70 % et d'écriture de 30 %, une taille de bloc de 8 Ko et une latence de 1 ms.
** *Débit* : Pour ONTAP 9.16.1 avec FCP, chaque instance de niveau de performance prend en charge l'accès séquentiel avec 100 % de lecture et une taille de bloc de 64 Ko.


* Pour le stockage AFX,
+
** *IOPS* : Pour ONTAP 9.18.1 avec NFSv4, chaque instance de niveau de performance prend en charge l'accès aléatoire avec un ratio de lecture de 70 % et d'écriture de 30 %, et une taille de bloc de 4 KB.
** *Débit* : Pour ONTAP 9.18.1 avec NFSv4, chaque instance de niveau de performance prend en charge l’accès séquentiel avec 100 % de lecture et une taille de bloc de 64 KB.


* La latence n'inclut pas les éléments suivants :
+
** latence de l'hôte ou de l'application
** latence du réseau du client vers ou depuis les ports du contrôleur
** Frais généraux associés au transfert des données vers le magasin d'objets en cas de FabricPool


* Les valeurs de latence ne s'appliquent pas aux opérations d'écriture MetroCluster. Ces opérations d'écriture dépendent de la distance entre les systèmes distants.
* La règle _IOPS attendues_ est destinée à FabricPool uniquement si la règle de Tiering est définie sur « aucun » et qu'aucun bloc n'est dans le cloud. _IOPS attendues_ est destiné aux volumes qui ne font pas partie d'une relation synchrone SnapMirror.




[[performance-service-levels-for-object-storage]]
== Niveaux de service de performance pour le stockage d'objets

|===


| *Niveau de service de performance* | *Standard* | *Valeur* 


| *Protocole pris en charge* 2+| S3 


| *Plate-forme* | SGF6112 | SG6160 


| *Capacité minimale engagée par commande* | 200 Tio | 500 Tio 


| *Augmentation progressive de la capacité engagée* | 25 Tio | 100 Tio 


| *Type de capacité engagée et mesurée* 2+| Physique 
|===


[[cloud-storage]]
== Le stockage cloud

|===


| *Niveau de service de performance* | *Cloud Volumes ONTAP* 


| *Protocoles pris en charge* | NFS, CIFS, iSCSI et S3 (AWS et Azure uniquement) 


| *Plate-forme* | Cloud Volumes ONTAP 


| *Capacité minimale engagée par commande* | 4 Tio 


| *Augmentation progressive de la capacité engagée* | 1 Tio 


| *Type de capacité engagée et mesurée* | Logique 
|===
[NOTE]
====
* Les services cloud natifs, tels que le calcul, le stockage et la mise en réseau, sont facturés par les fournisseurs cloud.
* Ces services dépendent de caractéristiques de stockage et de calcul cloud.


====
*Informations connexes*

* link:../concepts/supported-storage-capacity.html["Types de capacité de stockage dans Keystone"]
* link:..//concepts/metrics.html["Mesures et définitions utilisées dans les services Keystone"]
* link:../concepts/pricing.html["Tarification Keystone"]

