---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: 'Utilisez le site d"assistance NetApp pour créer une demande d"assistance ou trouver les informations de contact relatives à vos abonnements Keystone.' 
---
= Obtenez de l'aide avec Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp fournit aux clients Keystone des services opérationnels. Les clients reçoivent un Keystone Success Manager (KSM) dédié, des options de contact direct pour le support et une surveillance proactive via la solution ITOM.



== Services de support NetApp

NetApp fournit des services opérationnels à distance aux clients Keystone. Ces services couvrent un large éventail d’activités de gestion du stockage, notamment la gestion des actifs et de la configuration, la gestion de la capacité et des performances, la gestion des modifications, la gestion des événements et des incidents, le traitement des demandes de service et la production de rapports.

.Gestionnaire de réussite de Keystone
Votre KSM travaille en étroite collaboration avec vous sur vos services Keystone et vous fournit des rapports de facturation et d'exploitation hebdomadaires ou mensuels. Les responsabilités spécifiques sont définies dans votre accord NetApp Keystone.



== Contactez l'assistance

Si vous rencontrez un problème avec votre abonnement Keystone, connectez-vous au link:https://support.netapp.com["Site de support NetApp"^] à l'aide de vos identifiants NSS pour créer une demande d'assistance.

Si vous ne disposez pas d'un identifiant NSS, link:https://mysupport.netapp.com/site/user/registration["Enregistrez votre compte"^] utilisez le numéro de série (SN) de l'un des nœuds de votre abonnement.

Pour des instructions étape par étape avec captures d'écran, voir link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["Comment ouvrir un ticket d'assistance technique"^].

Si vous préférez parler directement avec un représentant du service d'assistance, veuillez composer l'un des numéros suivants :

* États-Unis / Canada: 888 463 8277
* Europe : 00 800 44 638277
* Inde: 000 800 100 8948
* Plus de chiffres mondiaux :link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== Surveillance du support

NetApp utilise la solution de surveillance ITOM pour surveiller de manière proactive l'état de vos produits et services souscrits et se connecter à l'environnement NetApp Keystone pour le dépannage.



== Ressources supplémentaires

Pour en savoir plus sur les services Keystone, consultez :

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["Documentation produit NetApp"^]


*Informations connexes*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["Comment identifier le numéro de série de la plateforme ONTAP"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["Quel numéro de série utiliser lors de la création d'une demande d'assistance technique StorageGRID"^]

