---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Capacités de stockage prises en charge 
---
= Capacités de stockage prises en charge dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les fonctionnalités du service NetApp Keystone STaaS sont les suivantes :



== Capacité logique

Il s'agit des données placées sur l'infrastructure Keystone par un client. Toutes les capacités Keystone font référence à une capacité logique. Par exemple, si un fichier de 1 Tio est stocké sur l'infrastructure Keystone, vous devez acheter un minimum de 1 Tio de capacité.



== De la capacité

La capacité logique minimale facturée chaque mois pendant l'abonnement :

* La capacité s'engage à chaque niveau de service.
* Il est possible d'ajouter de la capacité dédiée et des niveaux de service supplémentaires pendant la période de validité.




=== Modifications de la capacité engagée

Pendant la durée d'un abonnement, vous pouvez modifier les capacités engagées. Toutefois, il existe certaines conditions préalables :

* La capacité engagée peut être réduite en fonction de certaines conditions. Pour plus d'informations, reportez-vous à la section link:../concepts/capacity-requirements.html["Réduction de capacité"].
* La capacité engagée ne peut pas être augmentée 90 jours avant l'expiration de votre abonnement, à moins que l'abonnement ne soit renouvelé pour une durée supplémentaire de 12 mois.
* Vous pouvez demander des modifications de la capacité engagée via l'interface BlueXP ou via Keystone Success Manager (KSM). Pour plus d'informations sur la demande de modifications, reportez-vous à la section link:../concepts/gssc.html["Centre de support NetApp Global Services"].




== Capacité consommée

La capacité consommée fait référence à la capacité (en Tio de stockage) actuellement consommée sur le service. Le service Keystone prend en compte la somme des tailles logiques utilisées (et non de la capacité physique utilisée) de tous les volumes d'un niveau de services spécifique pour calculer la capacité consommée pour ce niveau de service.



== Capacité en rafale

La capacité en rafale est la capacité de tout type de consommation dépassant la capacité engagement d'un niveau de services.


NOTE: Remarque :

* Le service Keystone vous permet d'utiliser de la capacité supplémentaire en plus de la capacité validée pour un niveau de service. Il s'agit de la capacité en rafale.
* En effet, la capacité en rafale peut être consommée selon une base élastique et elle est facturée quotidiennement pour la moyenne utilisée.
* La capacité en rafale est convenue dans le contrat Keystone. Il est généralement configuré jusqu'à 20 % au-dessus de la capacité engagée et est facturé au même rythme que la capacité engagée.




== Capacité facturée

Facture mensuelle = (capacité de production [Tio] * taux d'engagement [$/Tio]) + (capacité moyenne approvisionnée par jour [Tio] * taux de bursting [$/Tio]). La facture mensuelle contient un montant minimal en fonction de la capacité engagée.

La facture mensuelle varie au-delà de la charge minimale, en fonction de la consommation moyenne quotidienne de capacité en rafale.
