---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Les services Keystone de stockage en tant que service prennent en charge ONTAP et StorageGRID. 
---
= Stockage pris en charge dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS prend en charge le stockage unifié, optimisé pour les blocs, AFX et objet sur les plateformes NetApp, ainsi que Cloud Volumes ONTAP. Chaque type de stockage est défini comme un type de stockage des données (DST) et est disponible avec les services standard inclus dans l’abonnement de base, ainsi qu’avec des services complémentaires optionnels.



[[keystone-staas-standard-and-add-on-services]]
== Services standard et complémentaires Keystone STaaS

Le service STaaS Keystone propose des services standard et facultatifs pour votre stockage.

*Les services STaaS standard Keystone* : les services standard sont inclus dans l'abonnement de base et ne sont pas facturés séparément.

*Les services complémentaires Keystone STaaS* : ce sont des services facultatifs payants qui offrent des utilitaires et des avantages supplémentaires en plus des services d'abonnement Keystone STaaS standard.

Vous pouvez souscrire à plusieurs services Keystone STaaS simultanément. Lorsque des services cloud sont ajoutés à un abonnement, ils partagent la même durée que le stockage unifié, le stockage optimisé par blocs et/ou le stockage objet. Un service cloud peut être ajouté à tout moment pendant la durée d'un abonnement de stockage actif. Toutefois, si vous ne prévoyez pas de renouveler un abonnement de stockage unifié, de stockage optimisé par blocs ou de stockage objet existant, aucun service cloud ne peut être ajouté durant les 90 derniers jours de cet abonnement.


NOTE: Un abonnement AFX est indépendant et ne peut être combiné avec un stockage unifié, un stockage optimisé bloc ou un stockage objet au sein du même abonnement. Si vous avez besoin d'AFX en plus d'autres types de stockage, vous devez souscrire des abonnements distincts.



[[supported-data-storage-types]]
== Types de stockage des données pris en charge

Les services Keystone STaaS pour le stockage unifié, optimisé pour le stockage bloc, objet et AFX prennent en charge de multiples fonctionnalités et protocoles, et sont décrits dans le tableau suivant :

|===
| Type de stockage de données | Description | Plateforme | Protocoles | Fonctionnalités prises en charge 


 a| 
Unifié
 a| 
Inclut le stockage de fichiers, de blocs et d'objets S3
 a| 
ONTAP sur les systèmes AFF et FAS
 a| 
FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One



 a| 
Optimisé pour les blocs
 a| 
Comprend stockage bloc
 a| 
NVMe/TCP, NVMe/FC, FC, iSCSI
 a| 
FC et iSCSI
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One pour SAN



 a| 
AFX
 a| 
Inclut le stockage de fichiers et d'objets sur une plateforme de stockage désagrégée
 a| 
ONTAP sur les systèmes AFX
 a| 
NFSv3, NFSv4/RDMA, pNFS, SMB, S3
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One



 a| 
Objet
 a| 
Comprend le stockage d'objets
 a| 
StorageGRID
 a| 
S3
 a| 
Prend en charge toutes les fonctionnalités de StorageGRID

|===
Pour en savoir plus sur ONTAP One, consultez link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Présentation des licences ONTAP"^] et link:https://www.netapp.com/blog/ontap-one/["ONTAP One : toute la puissance d'ONTAP, désormais tout en un"^] .



[[services-for-cloud-storage]]
== Services pour le stockage cloud

Le service STaaS Keystone propose des services de stockage cloud. Le service STaaS prend en charge les fonctionnalités de gestion des données Cloud Volumes ONTAP sur Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform.


NOTE: Les services de calcul, de stockage et de réseau basés sur des hyperscalers et requis par Cloud Volumes ONTAP ne sont pas fournis par NetApp dans le cadre des abonnements Keystone STaaS ; ces abonnements doivent être obtenus directement auprès des fournisseurs de service cloud hyperscalers.
