---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage service, service definition, keystone STaaS storage service, 
summary: Services de stockage pris en charge 
---
= Services de stockage pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service Keystone prend en charge les types de stockage de base de ONTAP, de fichier et de bloc. Il prend également en charge le stockage objet pour la plateforme StorageGRID et ses fonctionnalités de gestion des données pour Cloud Volumes ONTAP.

Pour plus d'informations sur les niveaux de service, reportez-vous à la section link:../concepts/service-levels.html["Niveaux de service dans Keystone"].



== Services de stockage de base

Les services de stockage de base pour les fichiers et les blocs offrent des services de protection des données par défaut en exploitant les technologies NetApp, telles que SnapMirror, SnapVault et Snapshot. Le Tiering des données vers la cible de stockage NetApp est également inclus par défaut dans les niveaux de service de stockage en mode bloc et fichier. Vous pouvez en outre opter pour des services d'extension pour le Tiering et la protection des données. Pour plus d'informations sur les services complémentaires, reportez-vous à la section link:../concepts/adp.html["Protection avancée des données"] et link:../concepts/data-tiering.html["Tiering des données"].

|===
| Service de stockage | Base | Fonctionnalités prises en charge | Protocoles 


 a| 
Stockage de fichiers
| Basée sur la technologie ONTAP | Fonctionnalités ONTAP prises en charge : copies FlexVol FlexGroup Snapshot copies SnapMirror (asynchrones) SnapVault SnapLock Enterprise FabricPool/Tiering cloud SnapCenter de clonage (la licence est incluse, mais cela ne fait pas partie des services Keystone et aucune gestion garantie n'est fournie) | NFS et CIFS. 


 a| 
Stockage basé sur des blocs
| Basée sur la technologie ONTAP | Fonctionnalités ONTAP prises en charge : copies FlexVol FlexGroup Snapshot copies SnapMirror (asynchrones) SnapVault SnapLock Enterprise FabricPool/Tiering cloud SnapCenter de clonage (la licence est incluse, mais cela ne fait pas partie des services Keystone et aucune gestion garantie n'est fournie) | FC et iSCSI 


 a| 
Stockage objet
| Basé sur la plateforme StorageGRID | Prise en charge de plusieurs règles de gestion du cycle de vie des informations (ILM) sur plusieurs sites Remarque : chaque site doit avoir un abonnement séparé. | S3 
|===


== Services de stockage cloud

Keystone prend en charge les fonctionnalités de gestion des données pour Cloud Volumes ONTAP sur Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform. Ce service peut être associé à vos abonnements existants. Le service cloud peut être inclus à tout moment pendant la durée du service. Toutefois, si vous ne prévoyez pas de renouveler votre abonnement, vous ne pouvez pas inclure le service cloud au cours des 90 derniers jours de votre abonnement.


NOTE: NetApp ne fournit pas d'infrastructure de stockage et de calcul basée sur des hyperscalers dans vos abonnements Keystone : vous devez les procurer auprès d'un fournisseur de services cloud hyperscale.
