---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Découvrez les types de capacités de stockage prises en charge par le service NetApp Keystone STaaS pour la version 3. 
---
= Types de capacité de stockage dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS utilise plusieurs termes de capacité pour mesurer, réserver et facturer le stockage. Comprendre ces termes vous aidera à planifier votre abonnement et à interpréter vos rapports d'utilisation et vos factures.



== Capacité logique

Il s'agit de la quantité de capacité de stockage requise pour stocker les données utilisateur avant que les gains d'efficacité des données fournis par la baie de stockage ne soient appliqués.



== De la capacité

La capacité logique minimale facturée chaque mois pendant l'abonnement :

* La capacité est allouée à chaque instance de niveau de service de performance pour le stockage unifié ou optimisé par bloc, ou par cluster AFX.
* Des capacités engagées et des niveaux de service de performance supplémentaires peuvent être ajoutés au cours de la durée.




=== Modifications de la capacité engagée

Pendant la durée de votre abonnement, vous pouvez modifier les capacités engagées sous certaines conditions. Pour plus de détails sur les règles d'augmentation et de réduction des capacités, consultez link:../concepts/capacity-requirements.html["Exigences de capacité pour les niveaux de service de performance Keystone"]. Pour demander une modification, contactez votre Keystone Success Manager (KSM) ou link:../concepts/support-services.html["Support NetApp"].



== Capacité consommée

La capacité consommée correspond à la capacité (en Tio de stockage) actuellement utilisée par le service. Elle est calculée différemment selon le type de stockage des données :

* *Stockage unifié ou optimisé par bloc* : La capacité consommée est calculée en fonction du type de capacité (logique ou physique) sélectionné lors du processus de commande.  Le calcul est effectué par instance de niveau de service de performance.
+
.. *Capacité logique* : C'est la somme de :
+
*** Capacité logique mesurée, avant l'efficacité des données de la baie de stockage, pour stocker toutes les instances et tous les types de données client, tels que les copies, les copies en miroir, les versions et les clones.
*** Capacité physique utilisée pour stocker les métadonnées et les données différentielles des instantanés et de certains clones.
*** Toute capacité physique provisionnée de manière épaisse.


.. *Capacité physique* : C'est la somme de :
+
*** Capacité physique mesurée, après optimisation des données de la baie de stockage, pour stocker toutes les instances et tous les types de données client, tels que les copies, les copies en miroir, les versions et les clones.
*** Capacité physique utilisée pour stocker les métadonnées et les données différentielles des instantanés.
*** Toute capacité physique provisionnée de manière épaisse.




* *Stockage AFX* : Il est calculé par cluster AFX comme la somme de :
+
** Capacité physique mesurée, après optimisation des données de la baie de stockage, pour stocker toutes les instances et tous les types de données client, tels que les copies, les copies en miroir, les versions et les clones.
** Capacité physique utilisée pour stocker les métadonnées et les données différentielles des instantanés.
** Toute capacité physique provisionnée de manière épaisse.


* *Stockage d'objets* : la capacité consommée correspond à la quantité de capacité physique mesurée utilisée pour stocker toutes les instances et tous les types de données client sur tous les nœuds. Ce calcul est basé sur les stratégies de gestion du cycle de vie de l'information (ILM) configurées.
* *Cloud Volumes ONTAP* : La capacité consommée est calculée comme la quantité de capacité logique provisionnée mesurée de tous les volumes Cloud Volumes ONTAP.




== Capacité en rafale

Le service NetApp Keystone STaaS vous permet d'utiliser une capacité supplémentaire en plus de la capacité engagée pour un niveau de service de performance donné. C'est ce qu'on appelle l'utilisation de capacité en rafale.

Notez ces points :

* La limite de capacité de pointe est convenue dans la commande Keystone. Elle est généralement fixée par défaut à 20 % au-dessus de la capacité engagée par instance de niveau de service de performance ou par cluster AFX, avec des options supplémentaires disponibles pour le stockage unifié et optimisé par blocs permettant de sélectionner des limites de capacité de pointe de 40 % ou 60 % de la capacité engagée.
* La consommation de capacité en rafale est facturée au même tarif que la capacité engagée correspondant au type de stockage des données (DST) et au niveau de service de performance sélectionnés.
* Les services Keystone STaaS offrent une période de renonciation de 60 jours à compter de la date de début.




== Capacité facturée

Facture mensuelle = (capacité de production [Tio] * taux d'engagement [$/Tio]) + (capacité moyenne approvisionnée par jour [Tio] * taux de bursting [$/Tio]). La facture mensuelle contient un montant minimal en fonction de la capacité engagée.

La facture mensuelle varie au-delà de la charge minimale, en fonction de la consommation moyenne quotidienne de capacité en rafale.
