---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: 'Si vous avez besoin d"aide, contactez l"équipe de support NetApp Keystone.' 
---
= Obtenez de l'aide avec Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'équipe de support NetApp Keystone et le responsable de la réussite Keystone (KSM) sont chargés de vous fournir le service nécessaire pour vos abonnements Keystone. Si vous avez besoin d'aide, contactez l'équipe de support Keystone.



== Prise en charge de NetApp Keystone

NetApp propose des services d'exploitation à distance aux clients NetApp Keystone. Ces services englobent diverses disciplines opérationnelles dans l'ensemble des activités de gestion du stockage. Il s'agit notamment de la gestion des ressources et de la configuration, de la gestion de la capacité et des performances, de la gestion des changements, des événements, de la gestion des incidents et des problèmes, de l'exécution des demandes de service et des rapports. NetApp démontre un état de contrôle et des preuves à l'appui, le cas échéant.



== Informations supplémentaires

NetApp utilise la solution de surveillance ITOM pour surveiller de manière proactive l'environnement NetApp Keystone et se connecter à celui-ci à des fins de dépannage.


NOTE: Dans un modèle opéré par les partenaires, les demandes de service des locataires et des sous-locataires sont attribuées au centre de service du partenaire. L'outil de support du partenaire peut être intégré à la solution ITOM.

Pour en savoir plus sur les services Keystone, consultez :

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentation produit NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Surveillance du support Keystone

Le support NetApp Keystone surveille l'état de vos produits et services souscrits, fournit un support à distance et collabore avec Keystone Success Manager.

.Gestionnaire de réussite de Keystone
Le gestionnaire de réussite Keystone (KSM) travaille en étroite collaboration avec vous pour vous aider à gérer vos services Keystone. Il vous informe sur la facturation hebdomadaire ou mensuelle et les rapports opérationnels. Les responsabilités sont précisées dans l'accord NetApp Keystone.



== Génération de demandes de service

Lors de votre intégration, si vous avez reçu les informations d'identification pour accéder à NetApp Keystone ServiceNow, vous pouvez utiliser le portail pour générer des demandes de service pour les problèmes liés à vos abonnements Keystone :

https://netappkeystone.service-now.com/csm[]

Assurez-vous que vous disposez des informations système, des journaux et des informations associées avant de lancer la demande de service. Lorsque vous faites une demande de service, l'équipe de support Keystone reçoit le ticket de support et accède aux informations de résolution de problèmes. Vous pouvez suivre votre ticket ServiceNow pour connaître l'état et la résolution du problème.

Pour plus d'informations sur l'ajout de modules de support, reportez-vous à la section link:../installation/monitor-health.html["Générer et collecter un bundle de support"].

Si votre dossier/ticket ouvert doit être réaffecté de la manière suivante, envoyez un e-mail à l'une des adresses suivantes : keystone.services@netapp.com keystone.escalations@netapp.com
