---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Les services Keystone de stockage en tant que service prennent en charge ONTAP et StorageGRID. 
---
= Stockage pris en charge dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service Keystone STaaS prend en charge le stockage unifié, optimisé par blocs et d'objets de NetApp et Cloud Volumes ONTAP.

Les options de stockage prises en charge sont :

* *Stockage unifié* : inclut le stockage de fichiers, de blocs et d'objets S3, disponible sur les systèmes NetApp ONTAP AFF et FAS.
* *Stockage optimisé par bloc* : inclut le stockage par bloc disponible sur les systèmes NetApp ONTAP ASA .
* *Stockage d'objets* : inclut le stockage d'objets disponible sur les systèmes NetApp StorageGRID.


Le service STaaS Keystone propose des services standard et facultatifs pour votre stockage.

*Les services STaaS standard Keystone* : les services standard sont inclus dans l'abonnement de base et ne sont pas facturés séparément.

*Les services complémentaires Keystone STaaS* : ce sont des services facultatifs payants qui offrent des utilitaires et des avantages supplémentaires en plus des services d'abonnement Keystone STaaS standard.

Les services Keystone STaaS peuvent être utilisés simultanément. Par exemple, un abonnement de stockage cloud peut avoir la même durée que les abonnements de stockage unifié, optimisé par blocs ou objet. Un service Cloud peut être inclus à tout moment pendant la durée de service d'un abonnement au stockage existant. Cependant, si vous ne prévoyez pas de renouveler un abonnement de stockage unifié, optimisé par blocs ou objet existant, aucun abonnement de stockage cloud ne peut être ajouté pendant les 90 derniers jours de l'abonnement.



== Services de stockage unifié, optimisé par blocs et d'objets

Les services Keystone STaaS pour le stockage unifié, optimisé par blocs et d'objets prennent en charge plusieurs fonctionnalités et protocoles et sont décrits dans le tableau suivant :

|===
| Stockage | Plateforme | Protocoles | Fonctionnalités prises en charge 


 a| 
Le stockage unifié
 a| 
ONTAP
 a| 
NFS et CIFS
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One



 a| 
Stockage optimisé par blocs
 a| 
ONTAP
 a| 
FC et iSCSI
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One



 a| 
Stockage objet
 a| 
StorageGRID
 a| 
S3
 a| 
Prend en charge toutes les fonctionnalités d'ONTAP One

|===
Pour en savoir plus sur ONTAP One, consultez link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Présentation des licences ONTAP"^] et link:https://www.netapp.com/blog/ontap-one/["ONTAP One : toute la puissance d'ONTAP, désormais tout en un"^] .



== Services pour le stockage cloud

Le service STaaS Keystone propose des services de stockage cloud. Le service STaaS prend en charge les fonctionnalités de gestion des données Cloud Volumes ONTAP sur Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform.


NOTE: Les services de calcul, de stockage et de réseau basés sur des hyperscalers requis par Cloud Volumes ONTAP ne sont pas fournis par NetApp dans le cadre d'abonnements Keystone. Ces abonnements doivent être achetés directement auprès de fournisseurs de services cloud hyperscales.
