---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Services STaaS Keystone 
---
= Stockage pris en charge dans les services STaaS Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les services Keystone STaaS prennent en charge le stockage des fichiers et des blocs d'ONTAP, le stockage objet de la plateforme StorageGRID et les fonctionnalités de gestion des données d'Cloud Volumes ONTAP.

Le service STaaS Keystone propose des services standard et facultatifs pour votre stockage.

*Les services STaaS standard Keystone* : les services standard sont inclus dans l'abonnement de base et ne sont pas facturés séparément.

*Les services complémentaires Keystone STaaS* : ce sont des services facultatifs payants qui offrent des utilitaires et des avantages supplémentaires en plus des services d'abonnement Keystone STaaS standard.

Les services STaaS Keystone peuvent coexister les uns avec les autres. Par exemple, un abonnement au stockage cloud peut co-term avec des abonnements au stockage objet, bloc et fichier. Un service Cloud peut être inclus à tout moment pendant la durée de service d'un abonnement au stockage existant. Cependant, si vous ne prévoyez pas de renouveler un abonnement existant au fichier, au bloc et à l'objet, un abonnement au stockage cloud ne peut pas être ajouté au cours des 90 derniers jours de l'abonnement.



== Services pour le stockage fichier, bloc et objet

Les services Keystone STaaS pour le stockage de fichiers et de blocs ONTAP, ainsi que le stockage objet StorageGRID, prennent en charge plusieurs fonctionnalités et protocoles, et sont décrits dans le tableau suivant :

|===
| Stockage | Plateforme | Protocoles | Fonctionnalités prises en charge 


 a| 
Stockage de fichiers
 a| 
ONTAP
 a| 
NFS et CIFS
 a| 
Fonctionnalités ONTAP prises en charge :

* FlexVol
* FlexGroup
* Copies Snapshot
* SnapMirror (asynchrone)
* SnapVault
* SnapLock Enterprise
* Tiering dans le cloud/FabricPool
* SnapRestore
* FlexClone
* SnapCenter (la licence est incluse, mais ne fait pas partie des services Keystone et la gestion n'est pas garantie)




 a| 
Stockage basé sur des blocs
 a| 
ONTAP
 a| 
FC et iSCSI
 a| 
Fonctionnalités ONTAP prises en charge :

* FlexVol
* FlexGroup
* Copies Snapshot
* SnapMirror (asynchrone)
* SnapVault
* SnapLock Enterprise
* Tiering dans le cloud/FabricPool
* SnapRestore
* FlexClone
* SnapCenter (la licence est incluse, mais ne fait pas partie des services Keystone et la gestion n'est pas garantie)




 a| 
Stockage objet
 a| 
StorageGRID
 a| 
S3
 a| 
Prise en charge de plusieurs règles de gestion du cycle de vie des informations (ILM) sur plusieurs sites *Remarque* : chaque site nécessite un abonnement séparé.

|===


== Services pour le stockage cloud

Le service STaaS Keystone propose des services de stockage cloud. Le service STaaS prend en charge les fonctionnalités de gestion des données Cloud Volumes ONTAP sur Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform.


NOTE: Les services de calcul, de stockage et de réseau basés sur des hyperscalers requis par Cloud Volumes ONTAP ne sont pas fournis par NetApp dans le cadre d'abonnements Keystone. Ces abonnements doivent être achetés directement auprès de fournisseurs de services cloud hyperscales.
