---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Add-on, Détails des services supplémentaires, Tiering des données 
---
= Tiering des données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Par défaut, les services de base Keystone incluent des fonctionnalités de Tiering avec vos services de fichiers et de blocs souscrits qui identifient les données moins fréquemment utilisées et les hiérarchise dans un stockage à froid qui est détenu, déployé et géré par NetApp. Vous pouvez utiliser le Tiering à titre d'extension si vous souhaitez hiérarchiser vos données inactives vers n'importe quel stockage non NetApp, tel que tout stockage cloud d'entreprise.

Le service d'extension de Tiering n'est nécessaire que lorsque les données sont envoyées vers un stockage non-NetApp, tel qu'Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP), et d'autres systèmes de stockage objet tiers compatibles S3 pris en charge.

Pour plus d'informations sur le service de stockage de base et de stockage cloud, voir link:../concepts/supported-storage-services.html["Services de stockage pris en charge"].

Pour plus d'informations sur les niveaux de service, reportez-vous à la section link:../concepts/service-levels.html["Niveaux de service dans Keystone"].

La fonctionnalité de Tiering exploite la technologie NetApp FabricPool qui permet le Tiering automatisé des données vers des tiers de stockage objet à faible coût, sur site ou hors site. Les données rarement utilisées sont ainsi automatiquement transférées vers un stockage à moindre coût sur site ou dans le cloud, en fonction des services convenus.

Le service de Tiering complémentaire permet de Tiering depuis les niveaux Extreme, Premium, Performance, Standard et Value Tier vers la cible objet. Le Tier actif et le Tier à froid sont mesurés et facturés séparément.

Le Tiering peut être ajouté à tout moment, sans modification du prix, ce qui offre plus de flexibilité en termes de ratio chaud/froid. Le rapport entre les données fortement sollicitées et les données inactives à hiérarchiser n'est pas fixe et le nombre de blocs physiques hiérarchisés est mesuré séparément.

Pour plus d'informations, consultez les calculs suivants :

Si la cible pour un Tier de stockage à froid est :

* Tier de valeur (jusqu'à 500 Tio), Tier d'objet (500Tio), réseau SGWS existant (propriété du client) : il n'y a aucun frais supplémentaire. Il fait partie du service de stockage de base.
* Le cloud public (AWS, Azure, Google) et tout autre stockage objet pris en charge par un tiers : la capacité de stockage supplémentaire est facturé pour ce qui est du Tier de stockage.


Les frais liés à l'abonnement à la hiérarchisation du service complémentaire ne sont pas des frais unique. Vous devez payer à l'IT pendant toute la durée du terme pour maintenir la relation de Tiering entre Keystone avec des services de fichiers et de blocs sur site, et la cible de stockage objet prise en charge par le tiers.

Il est ainsi possible de transférer uniquement les données inactives vers un système de stockage cible moins onéreux, et non vers une infrastructure de cloud public/Hyperscalers.


NOTE: NetApp ne fournit pas d'infrastructure de stockage et de calcul basée sur des hyperscalers dans vos abonnements Keystone : vous devez les procurer auprès d'un fournisseur de services cloud hyperscale.
