---
sidebar: sidebar 
permalink: concepts/usps-v2.html 
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support 
summary: Le support protégé des États-Unis est un service complémentaire qui fournit la livraison et le support des services Keystone en continu de citoyens américains sur le sol américain. 
---
= En savoir plus sur USPS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le support protégé aux États-Unis (USPS) est une offre complémentaire aux abonnements NetApp Keystone. Elle vous donne droit à la livraison et à l'assistance des services Keystone en cours de la part de citoyens américains sur le sol américain.

Lisez les sections suivantes pour comprendre quels éléments de vos abonnements sont liés par ce service complémentaire et sont fournis conformément aux termes de l'Accord de NetApp Keystone.Note de bas de page:disréclamation 1[les services et offres décrits ici sont sujets, limités et régis par un contrat Keystone pleinement exécuté.]



== Surveillance NetApp USPS

L'équipe de support NetApp USPS Keystone surveille l'état de vos produits et services souscrits, fournit un support à distance et collabore avec Keystone Success Manager. L'ensemble du personnel chargé de surveiller les produits associés aux commandes d'abonnement Keystone correspondantes est de type U. S citoyens opérant sur le sol américain.



== Gestionnaire de réussite de Keystone

Le responsable de la réussite Keystone (KSM) est un département américain Vivant sur le sol américain. Leurs responsabilités sont précisées dans votre contrat NetApp Keystone.



== Activités de déploiement

Le cas échéant, les activités de déploiement et d'installation sur site et à distance sont menées par les États-Unis Citoyens américains américain. Note de bas de page :Avis de non-responsabilité[la disponibilité du personnel approprié pour les activités sur site dépend de l'emplacement géographique où les systèmes Keystone sont déployés.]



== Assistance

Le cas échéant, les activités de support et de dépannage sur site sont menées par les États-Unis Citoyens américains américain. note de bas de page:disclaimer[]
