---
sidebar: sidebar 
permalink: installation/addl-req.html 
keywords: keystone unified manager prerequisites, aiqum config keystone 
summary: 'conditions préalables à l"utilisation d"un gestionnaire unifié keystone' 
---
= Conditions préalables supplémentaires pour ONTAP et StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez remplir quelques conditions préalables supplémentaires pour ONTAP et StorageGRID. Assurez-vous d'avoir rempli ces conditions préalables spécifiques en plus de la configuration système requise pour Linux/VMware vSphere. Cliquez sur l'onglet requis pour en savoir plus.

[role="tabbed-block"]
====
.ONTAP
--
Pour installer le collecteur Keystone dans ONTAP, effectuez les étapes suivantes en tant que conditions préalables :

. Vérifiez qu'un serveur Active IQ Unified Manager (Unified Manager) est configuré avec Unified Manager 9.7 ou une version ultérieure. Pour plus d'informations sur l'installation de Unified Manager, consultez les liens suivants :
+
** https://["Installation de Unified Manager sur des systèmes VMware vSphere"^]
** https://["Installation de Unified Manager sur des systèmes Linux"^]


. Vérifiez que le cluster ONTAP a été ajouté à Unified Manager. Pour plus d'informations sur l'ajout de clusters, reportez-vous à la section https://["Ajout de clusters"^].
. Créez des utilisateurs Unified Manager avec des rôles spécifiques pour la collecte de données sur l'utilisation et les performances. Procédez comme suit. Pour plus d'informations sur les rôles d'utilisateur, reportez-vous à la section https://["Définitions des rôles utilisateur"^].
+
.. Connectez-vous à l'interface utilisateur Web d'Unified Manager à l'aide des informations d'identification utilisateur par défaut de l'administrateur de l'application générées lors de l'installation. Voir https://["Accès à l'interface utilisateur Web de Unified Manager"^].
.. Créez un compte de service pour Keystone Collector avec `Operator` rôle utilisateur. Les API du service Keystone Collector utilisent ce compte de service pour communiquer avec Unified Manager et collecter les données d'utilisation. Voir https://["Ajout d'utilisateurs"^].
.. Créer un `Database` compte utilisateur, avec le `Report Schema` rôle. Cet utilisateur est requis pour la collecte des données de performances. Voir https://["Création d'un utilisateur de base de données"^].


. Activez API Gateway dans Unified Manager. Keystone Collector utilise la fonctionnalité de passerelle d'API pour communiquer avec les clusters ONTAP. Vous pouvez activer la passerelle d'API depuis l'interface utilisateur Web ou en exécutant quelques commandes via l'interface de ligne de commande Unified Manager.
+
.Interface utilisateur Web
Pour activer API Gateway à partir de l'interface utilisateur Web d'Unified Manager, connectez-vous à l'interface utilisateur Web d'Unified Manager et activez API Gateway. Pour plus d'informations, reportez-vous à la section https://["Activation de la passerelle API"^].

+
.CLI
Pour activer la passerelle d'API via l'interface de ligne de commande d'Unified Manager, effectuez la procédure suivante :

+
.. Sur le serveur Unified Manager, démarrez une session SSH et connectez-vous à l'interface de ligne de commande d'Unified Manager.
`um cli login -u _<umadmin>_`Pour plus d'informations sur les commandes CLI, reportez-vous à la section https://["Commandes CLI Unified Manager prises en charge"^].
.. Vérifiez si la passerelle API est déjà activée.
`um option list api.gateway.enabled`A `true` Valeur indique que la passerelle d'API est activée.
.. Si la valeur renvoyée est `false`, exécutez la commande suivante :
`um option set api.gateway.enabled=true`
.. Redémarrez le serveur Unified Manager :
+
*** Linux : https://["Redémarrage de Unified Manager"^].
*** VMware vSphere : https://["Redémarrage de la machine virtuelle Unified Manager"^].






--
.StorageGRID
--
Les configurations suivantes sont requises pour l'installation de Keystone Collector sur StorageGRID.

* StorageGRID `11.4.0` ou une version ultérieure doit être installée. Pour plus d'informations sur la mise à niveau de StorageGRID, voir link:https://docs.netapp.com/us-en/storagegrid-116/upgrade/index.html["Mettre à niveau le logiciel StorageGRID : présentation"^].
* Un compte utilisateur admin local StorageGRID doit être créé pour la collecte des données d'utilisation. Ce compte de service est utilisé par le service Keystone Collector pour communiquer avec StorageGRID via les API du nœud administrateur.
+
.Étapes
.. Connectez-vous au Gestionnaire de grille. Voir https://["Connectez-vous au Grid Manager"^].
.. Créez un groupe d'administration local avec `Access mode: Read-only`. Voir https://["Créer un groupe d'administration"^].
.. Ajoutez les autorisations suivantes :
+
*** Comptes de locataires
*** Maintenance
*** Requête de metrics


.. Créez un utilisateur de compte de service Keystone et associez-le au groupe d'administration. Voir https://["Gérer les utilisateurs"].




--
====