---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: Procédure de configuration de AutoSupport pour Keystone 
---
= Configurez AutoSupport pour Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de l'utilisation du mécanisme de télémétrie AutoSupport, le service Keystone effectue des mesures de l'utilisation en fonction des données de télémétrie AutoSupport. Pour atteindre le niveau de granularité nécessaire, vous devez configurer AutoSupport de manière à intégrer les données Keystone dans les bundles de support quotidiens envoyés par les clusters ONTAP.

.Avant de commencer
Avant de configurer AutoSupport pour inclure des données Keystone, veillez à noter les points suivants.

* Vous pouvez modifier les options de télémétrie AutoSupport à l'aide de l'interface de ligne de commande ONTAP. Pour plus d'informations sur la gestion des services AutoSupport et du rôle d'administrateur système (cluster), reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["Présentation de Manage AutoSupport"^] et https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["Administrateurs Cluster et SVM"^].
* Vous incluez les sous-systèmes suivants dans les bundles AutoSupport quotidiens pour garantir la collecte précise des données pour Keystone. Pour plus d'informations sur les sous-systèmes AutoSupport, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["Nature des sous-systèmes AutoSupport"^].
+
|===
| Nom du sous-système | Élément de données requis pour Keystone 


 a| 
WAFL
| `VOLUME-CLONE-SHOW.XML` 


 a| 
performances
| `QOS-POLICY-GROUP.XML` et `QOS-ADAPTIVE-POLICY.XML` 


 a| 
snapshot
| `SNAPSHOT.XML` 


 a| 
plateforme
| `ENVIRONMENT.txt` 
|===
+
Ces sous-systèmes sont inclus par défaut dans les packs AutoSupport hebdomadaires, où l' `asup_type` Est _DOT-REGULAR_, et le `asup_subject` Est _NOTIFICATION de groupe HA (HEBDOMADAIRE_LOG) AVIS_. Cependant, vous devez les ajouter aux bundles quotidiens pour récupérer et générer des rapports sur les données d'utilisation Keystone.



.Étapes
. En tant qu'administrateur système, connectez-vous au cluster Keystone ONTAP à l'aide de SSH. Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["Accéder au cluster via SSH"^].
. Exécutez la commande suivante et vérifiez la configuration existante par rapport aux sous-systèmes existants :
+
`autosupport trigger show -node * -autosupport-message management.log -fields basic-additional`

+
Pour plus d'informations sur cette commande, voir https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-manifest-show.html#parameters["le manifeste AutoSupport du nœud système s'affiche"^].

. Modifiez le contenu du journal quotidien en exécutant cette commande :
+
`autosupport trigger modify -node * -autosupport-message management.log -basic-additional _<existing comma-separated subsystems>_, _<new subsystems>_`

+
Pour plus d'informations sur cette commande, voir https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["modification du déclencheur AutoSupport du nœud système"^].


