---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: Procédure de configuration de AutoSupport pour Keystone 
---
= Configurez AutoSupport pour Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lorsque vous utilisez le mécanisme de télémétrie AutoSupport, Keystone calcule l'utilisation en fonction des données de télémétrie AutoSupport. Pour atteindre le niveau de granularité nécessaire, vous devez configurer AutoSupport de manière à intégrer les données Keystone dans les bundles de support quotidiens envoyés par les clusters ONTAP.

.Description de la tâche
Avant de configurer AutoSupport pour inclure des données Keystone, veillez à noter les points suivants.

* Vous pouvez modifier les options de télémétrie AutoSupport à l'aide de l'interface de ligne de commande ONTAP. Pour plus d'informations sur la gestion des services AutoSupport et du rôle d'administrateur système (cluster), reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["Présentation de Manage AutoSupport"^] et https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["Administrateurs Cluster et SVM"^].
* Vous incluez les sous-systèmes dans les bundles AutoSupport quotidiens et hebdomadaires pour garantir la collecte précise des données pour Keystone. Pour plus d'informations sur les sous-systèmes AutoSupport, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["Nature des sous-systèmes AutoSupport"^].


.Étapes
. En tant qu'administrateur système, connectez-vous au cluster Keystone ONTAP à l'aide de SSH. Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["Accéder au cluster via SSH"^].
. Modifier le contenu du journal.
+
** Exécutez cette commande pour modifier le contenu du journal quotidien :
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,platform,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
** Exécutez cette commande pour modifier le contenu du journal hebdomadaire :
+
[source]
----
autosupport trigger modify -autosupport-message weekly -troubleshooting-additional wafl -node *
----
+
Pour plus d'informations sur cette commande, voir https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["modification du déclencheur AutoSupport du nœud système"^].




