---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: 'Préparez votre système Linux avec les logiciels requis avant d"installer Keystone Collector.' 
---
= Configuration système requise pour Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La préparation de votre système Linux avec le logiciel requis garantit une installation et une collecte de données précises par Keystone Collector.

Assurez-vous que votre VM serveur Linux et Keystone Collector possède ces configurations.

.Serveur Linux :
* Système d'exploitation : l'un des systèmes suivants :
+
** Debian 12
** Red Hat Enterprise Linux 8.6 ou versions ultérieures 8.x.
** CentOS 7 (pour les environnements existants uniquement)


* Temps Chronyd synchronisé
* Accès aux référentiels logiciels Linux standard


Le même serveur doit également avoir les packages tiers suivants :

* Podman (Manager POD)
* sos
* chrony
* python 3 (3.6.8 à 3.9.13)


.Serveur virtuel Keystone Collector :
* Cœur : 2 processeurs
* RAM : 4 GO DE RAM
* Espace disque : 50 Go de vDisk




== Autres exigences

S'assurer que les exigences génériques suivantes sont respectées :



=== Exigences de mise en réseau

Les exigences de mise en réseau de Keystone Collector sont répertoriées dans le tableau suivant.


NOTE: Keystone Collector nécessite une connectivité Internet. Vous pouvez fournir une connectivité Internet par routage direct via la passerelle par défaut (via NAT) ou via le proxy HTTP. Les deux variantes sont décrites ici.

|===


| Source | Destination | Service | Protocole et ports | Catégorie | Objectif 


 a| 
Collecteur Keystone (pour Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatoire (en cas d'utilisation de Keystone ONTAP)
 a| 
Collecte de metrics d'utilisation du collecteur Keystone pour ONTAP



 a| 
Collecteur Keystone (pour Keystone StorageGRID)
 a| 
Nœuds d'administration StorageGRID
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatoire (en cas d'utilisation de Keystone StorageGRID)
 a| 
Collecte de metrics d'utilisation du collecteur Keystone pour StorageGRID



 a| 
Collecteur Keystone (générique)
 a| 
Internet (conformément aux exigences d'URL fournies ultérieurement)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatoire (connectivité Internet)
 a| 
Le logiciel Keystone Collector, les mises à jour du système d'exploitation et le téléchargement de metrics



 a| 
Collecteur Keystone (générique)
 a| 
Proxy HTTP client
 a| 
Proxy HTTP
 a| 
Port proxy client
 a| 
Obligatoire (connectivité Internet)
 a| 
Le logiciel Keystone Collector, les mises à jour du système d'exploitation et le téléchargement de metrics



 a| 
Collecteur Keystone (générique)
 a| 
Serveurs DNS du client
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatoire
 a| 
Résolution DNS



 a| 
Collecteur Keystone (générique)
 a| 
Serveurs NTP du client
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatoire
 a| 
Synchronisation de l'heure



 a| 
Collecteur Keystone (pour Keystone ONTAP)
 a| 
Unified Manager
 a| 
MYSQL
 a| 
TCP 3306
 a| 
En option
 a| 
Collecte de metrics de performance pour Keystone Collector



 a| 
Collecteur Keystone (générique)
 a| 
Système de surveillance client
 a| 
HTTPS
 a| 
TCP 7777
 a| 
En option
 a| 
Reporting sur l'état du collecteur Keystone



 a| 
Postes de travail opérationnels du client
 a| 
Collecteur Keystone
 a| 
SSH
 a| 
TCP 22
 a| 
Gestion
 a| 
Accès à la gestion des collecteurs Keystone



 a| 
Adresses NetApp ONTAP de gestion de cluster et de nœud
 a| 
Collecteur Keystone
 a| 
HTTP_8000, PING
 a| 
TCP 8000, demande/réponse d'écho ICMP
 a| 
En option
 a| 
Serveur Web pour les mises à jour du micrologiciel ONTAP

|===

NOTE: Le port par défaut de MySQL, 3306, est limité à localhost uniquement lors d'une nouvelle installation d'Unified Manager, ce qui empêche la collecte des mesures de performances pour Keystone Collector. Pour plus d'informations, voir link:addl-req.html["Configuration requise pour ONTAP"].



=== Accès à l'URL

Le collecteur Keystone doit accéder aux hôtes Internet suivants :

|===


| Adresse | Raison 


 a| 
https://keystone.netapp.com[]
 a| 
Mises à jour logicielles Keystone Collector et rapports d'utilisation



 a| 
https://support.netapp.com[]
 a| 
Siège de NetApp, pour la facturation et la livraison AutoSupport

|===