---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Installez le logiciel Keystone Collector à partir du référentiel logiciel YUM. 
---
= Installez Keystone Collector sur les systèmes Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer le logiciel Keystone Collector sur un serveur Linux à l'aide d'un RPM ou d'un paquet Debian. Suivez les étapes d'installation en fonction de votre distribution Linux.

[role="tabbed-block"]
====
.Utilisation de RPM
--
. SSH vers le serveur Keystone Collector et passez à `root` privilège.
. Importer la signature publique de Keystone :
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Assurez-vous que le certificat public correct a été importé en vérifiant l'empreinte numérique de Keystone Billing Platform dans la base de données RPM :
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` L'empreinte digitale correcte ressemble à ceci :
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Téléchargez le `keystonerepo.rpm` déposer:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Vérifiez l'authenticité du fichier :
`rpm --checksig -v keystonerepo.rpm` La signature d'un fichier authentique ressemble à ceci :
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Installez le fichier de référentiel du logiciel YUM :
`# yum install keystonerepo.rpm`
. Lorsque Keystone repo est installé, installez le package trapèze-Collector via le gestionnaire de package YUM :
+
`# yum install keystone-collector`

+
Pour Red Hat Enterprise Linux 9, exécutez la commande suivante pour installer le package keystone-collector : 
`# yum install keystone-collector-rhel9`



--
.Utilisation de Debian
--
. SSH sur le serveur Keystone Collector et élever au `root` privilège.
`sudo su`
. Télécharger le `keystone-sw-repo.deb` fichier :
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Installez le fichier de référentiel du logiciel Keystone :
`# dpkg -i keystone-sw-repo.deb`
. Mettre à jour la liste des packages :
`# apt-get update`
. Une fois le référentiel Keystone installé, installez le package de collecteur Keystone :
`# apt-get install keystone-collector`


--
====

NOTE: Une fois l'installation terminée, vous pouvez utiliser l'utilitaire TUI (Keystone Collector Management terminal User interface) pour effectuer les activités de configuration et de surveillance. Vous pouvez utiliser diverses commandes du clavier, telles que les touches entrée et flèche, pour sélectionner les options et naviguer dans cette TUI. Voir link:../installation/configuration.html["Configurer le collecteur Keystone"] et link:../installation/monitor-health.html["Contrôle de l'état des systèmes"] pour plus d'informations.
