---
sidebar: sidebar 
permalink: installation/vapp-prereqs.html 
keywords: prerequisites, VMware vSphere, vApp 
summary: 'Conditions préalables à l"installation de Keystone Collector sur des systèmes VMware vSphere' 
---
= Besoins de l'infrastructure virtuelle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quelques configurations d'infrastructure virtuelle sont requises pour installer Keystone Collector sur vos systèmes VMware vSphere.

.Prérequis pour la machine virtuelle du serveur Keystone Collector :
* Système d'exploitation : serveur VMware vCenter et ESXi 6.5 ou version ultérieure
* Cœur : 4 processeurs
* RAM : 12 GO DE RAM
* Espace disque : disque virtuel de 200 Go




== Autres exigences

S'assurer que les exigences génériques suivantes sont respectées :



=== Exigences de mise en réseau

Les exigences de mise en réseau de Keystone Collector sont répertoriées dans le tableau suivant.


NOTE: Keystone Collector nécessite une connectivité Internet. Vous pouvez fournir une connectivité Internet par routage direct via la passerelle par défaut (via NAT) ou via le proxy HTTP. Les deux variantes sont décrites ici.

|===


| Source | Destination | Service | Protocole et ports | Catégorie | Objectif 


 a| 
Collecteur Keystone (pour Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatoire (en cas d'utilisation de Keystone ONTAP)
 a| 
Collecte de metrics d'utilisation du collecteur Keystone pour ONTAP



 a| 
Collecteur Keystone (pour Keystone StorageGRID)
 a| 
Nœuds d'administration StorageGRID
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatoire (en cas d'utilisation de Keystone StorageGRID)
 a| 
Collecte de metrics d'utilisation du collecteur Keystone pour StorageGRID



 a| 
Collecteur Keystone (générique)
 a| 
Internet (conformément aux exigences d'URL fournies ultérieurement)
 a| 
HTTP, HTTPS
 a| 
TCP 80, TCP 443
 a| 
Obligatoire (connectivité Internet)
 a| 
Le logiciel Keystone Collector, les mises à jour du système d'exploitation et le téléchargement de metrics



 a| 
Collecteur Keystone (générique)
 a| 
Proxy HTTP client
 a| 
Proxy HTTP
 a| 
Port proxy client
 a| 
Obligatoire (connectivité Internet)
 a| 
Le logiciel Keystone Collector, les mises à jour du système d'exploitation et le téléchargement de metrics



 a| 
Collecteur Keystone (générique)
 a| 
Serveurs DNS du client
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatoire
 a| 
Résolution DNS



 a| 
Collecteur Keystone (générique)
 a| 
Serveurs NTP du client
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatoire
 a| 
Synchronisation de l'heure



 a| 
Collecteur Keystone (pour Keystone ONTAP)
 a| 
Unified Manager
 a| 
MYSQL
 a| 
TCP 3306
 a| 
En option
 a| 
Collecte de metrics de performance pour Keystone Collector



 a| 
Collecteur Keystone (générique)
 a| 
Système de surveillance client
 a| 
HTTP
 a| 
TCP 777
 a| 
En option
 a| 
Reporting sur l'état du collecteur Keystone



 a| 
Postes de travail opérationnels du client
 a| 
Collecteur Keystone
 a| 
SSH
 a| 
TCP 22
 a| 
Gestion
 a| 
Accès à la gestion des collecteurs Keystone



 a| 
Adresses NetApp ONTAP de gestion de cluster et de nœud
 a| 
Collecteur Keystone
 a| 
HTTP_8000, PING
 a| 
TCP 8000, demande/réponse d'écho ICMP
 a| 
En option
 a| 
Serveur Web pour les mises à jour du micrologiciel ONTAP

|===


=== Accès à l'URL

Le collecteur Keystone doit accéder aux hôtes Internet suivants :

|===


| Adresse | Raison 


 a| 
https://[]
 a| 
Mises à jour logicielles Keystone Collector et rapports d'utilisation



 a| 
https://[]
 a| 
Siège de NetApp, pour la facturation et la livraison AutoSupport



 a| 
https://[]
https://[]
 a| 
Mises à jour du système d'exploitation pour Keystone Collector (déploiements OVA uniquement)



 a| 
https://[]
 a| 
Téléchargement et mise à jour des dépendances MySQL (pour les déploiements Linux uniquement)

|===