---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Les problèmes détectés dans les versions précédentes des services de stockage en tant que service NetApp Keystone ont été résolus dans les versions ultérieures. 
---
= Problèmes résolus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les problèmes détectés dans les versions précédentes des services de stockage en tant que service NetApp Keystone ont été résolus dans les versions ultérieures.

[cols="3*"]
|===
| Description du problème | Après la réparation | Corrigé dans la libération 


 a| 
Le champ *de la date* pour sélectionner la plage de dates affiche une date future par défaut lorsque vous accédez à l'onglet *tendance de consommation*.
 a| 
Fixe
 a| 
4 septembre 2024



 a| 
L'interface TUI de gestion du collecteur Keystone ne répond plus lors de la configuration des règles AQoS.
 a| 
Fixe
 a| 
7 août 2024



 a| 
Les graphiques d'utilisation affichent les données au-delà de la période d'une journée spécifiée lorsque la date correspondant au jour en cours est sélectionnée comme date de début et de fin pour le mois précédent à partir de l'option *Capacity Trend* de l'onglet *Capacity Trends*.
 a| 
Les graphiques d'utilisation affichent désormais correctement les données pour la période d'une journée spécifiée.
 a| 
27 juin 2024



 a| 
Les données historiques cumulées en rafale ne sont pas disponibles pour les niveaux de service *CVO primaire* et *CVO secondaire* dans l'onglet *tendance de capacité* pour les abonnements qui ne sont pas configurés avec une configuration MetroCluster.
 a| 
Fixe
 a| 
21 juin 2024



 a| 
Affichage incorrect de la valeur de consommation du stockage objet indiquée dans l'onglet *Détails du volume* pour les abonnements AutoSupport.
 a| 
La valeur consommée pour le stockage objet s'affiche désormais correctement.
 a| 
21 juin 2024



 a| 
Impossible d'afficher les informations au niveau du cluster dans l'onglet *Assets* pour les abonnements AutoSupport configurés avec une configuration MetroCluster.
 a| 
Fixe
 a| 
21 juin 2024



 a| 
Placement erroné des données Keystone dans les rapports CSV si la colonne *Nom du compte* dans les rapports CSV, générée à partir de l'onglet *tendance de capacité*, inclut un nom de compte avec une virgule `(,)`.
 a| 
Les données Keystone sont correctement alignées dans les rapports CSV.
 a| 
29 mai 2024



 a| 
Affichez l'utilisation de rafale accumulée à partir de l'onglet *Capacity Trend* même si la consommation est inférieure à la capacité allouée.
 a| 
Fixe
 a| 
29 mai 2024



 a| 
Texte d'info-bulle incorrect pour l'icône d'index *Burst* actuel dans l'onglet *Capacity Trend*.
 a| 
Affiche le texte correct de l'info-bulle «_la quantité de capacité de rafale actuellement consommée. Remarque : il s'agit de la période de facturation en cours et non de la plage de dates sélectionnée._ »
 a| 
28 mars 2024



 a| 
Les informations sur les volumes non conformes AQoS et les partenaires MetroCluster ne sont pas disponibles pour les abonnements AutoSupport si les données Keystone ne sont pas présentes pendant 24 heures.
 a| 
Fixe
 a| 
28 mars 2024



 a| 
Incohérence occasionnelle dans le nombre de volumes non conformes AQoS répertoriés dans les onglets *Volume Summary* et *Volume Details* si deux niveaux de service sont affectés à un volume qui satisfait à la conformité AQoS pour un seul niveau de service.
 a| 
Fixe
 a| 
28 mars 2024



 a| 
Aucune information n'est disponible dans l'onglet *Assets* pour les abonnements AutoSupport.
 a| 
Fixe
 a| 
14 mars 2024



 a| 
Si MetroCluster et FabricPool étaient tous deux activés dans un environnement où des plans de taux pour la hiérarchisation et le stockage objet étaient applicables, les niveaux de service pourraient être incorrectement dérivés pour les volumes en miroir (à la fois les volumes constituant et FabricPool).
 a| 
Des niveaux de service corrects sont appliqués aux volumes en miroir.
 a| 
29 février 2024



 a| 
Pour certains abonnements ayant un seul niveau de service ou un seul plan tarifaire, la colonne conformité AQoS était manquante dans la sortie CSV des rapports de l'onglet *volumes*.
 a| 
La colonne conformité est visible dans les rapports.
 a| 
29 février 2024



 a| 
Dans certains environnements MetroCluster, une anomalie occasionnelle a été détectée dans les graphiques de densité des IOPS de l'onglet *Performance*. Ce problème est dû à un mappage incorrect des volumes avec les niveaux de service.
 a| 
Les graphiques sont correctement affichés.
 a| 
29 février 2024



 a| 
L'indicateur d'utilisation d'un enregistrement de consommation en rafale était affiché en orange.
 a| 
L'indicateur apparaît en rouge.
 a| 
13 décembre 2023



 a| 
La plage de dates et les données des onglets tendance de la capacité, utilisation actuelle et performances n'ont pas été converties en fuseau horaire UTC.
 a| 
La plage de dates pour la requête et les données de tous les onglets s'affiche en heure UTC (fuseau horaire du serveur). Le fuseau horaire UTC est également affiché pour chaque champ de date sur les onglets.
 a| 
13 décembre 2023



 a| 
La date de début et la date de fin ne correspondent pas entre les onglets et les rapports CSV téléchargés.
 a| 
Fixe.
 a| 
13 décembre 2023

|===