---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations in Keystone STaaS 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limites connues
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les dispositifs ou les fonctions qui ne sont pas pris en charge par les services ou composants Keystone de STaaS ou qui ne fonctionnent pas correctement. Examinez attentivement ces limites.



== Limitations de Keystone Collector



=== Le collecteur Keystone ne peut pas démarrer sur vSphere 8.0 Update 1

Une machine virtuelle Keystone Collector avec VMware vSphere version 8.0 Update 1 ne peut pas être activée et le message d'erreur suivant s'affiche :

`Property 'Gateway' must be configured for the VM to power on.`

Consultez l'article de la base de connaissances link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_start_on_vSphere_8.0_U1["Le collecteur Keystone ne parvient pas à démarrer sur vSphere 8.0 U1"^] pour plus d'informations et pour la résolution.



=== Impossible de générer le bundle de support sur Kerberos

Si le répertoire local du collecteur Keystone est monté sur NFSv4 à l'aide de Kerberos, le bundle de support n'est pas généré et le message d'erreur suivant s'affiche :

`subprocess.CalledProcessError: Command '['sosreport', '--batch', '-q', '--tmp-dir', '/home/<user>']' returned non-zero exit status 1.`

Consultez l'article de la base de connaissances https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_generate_support_bundle_on_Kerberized_home_directory["Le collecteur Keystone ne parvient pas à générer le bundle de support sur le répertoire principal Kerberos"^] pour plus d'informations et pour la résolution.



=== Le collecteur Keystone ne peut pas communiquer avec les hôtes dans une plage réseau spécifique

Le collecteur Keystone ne peut pas communiquer avec les périphériques de la plage réseau 10.88.0.0/16 lorsque le système `ks-collector` le service est en cours d'exécution. Consultez l'article de la base de connaissances link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_container_conflict_with_customer_network["Conflit entre le conteneur du collecteur Keystone et le réseau client"^] pour plus d'informations et pour la résolution.



=== Le collecteur Keystone ne peut pas vérifier le certificat d'autorité de certification SSL racine du client

Si l'inspection SSL/TLS est activée au niveau du pare-feu frontalier dans un environnement pour inspecter le trafic SSL/TLS, le collecteur Keystone ne peut pas établir de connexion HTTPS, car le certificat d'autorité de certification racine du client n'est pas approuvé.

Pour plus d'informations sur la résolution, reportez-vous à la section link:..//installation/configuration.html#trust-a-custom-root-ca["Faites confiance à une autorité de certification racine personnalisée"^] Ou de la base de connaissance link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_cannot_verify_Customer_Root_SSL_CA_certificate["Le collecteur Keystone ne peut pas vérifier le certificat de l'autorité de certification SSL racine du client"^].
