---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Les problèmes connus identifient les problèmes qui pourraient vous empêcher d’utiliser Keystone efficacement. 
---
= Problèmes connus dans le stockage en tant que service Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les problèmes connus identifient les problèmes qui pourraient vous empêcher d’utiliser Keystone STaaS efficacement.

Les problèmes connus suivants sont rapportés dans NetApp Keystone STaaS :

[cols="3*"]
|===
| Problème connu | Description | Solution de contournement 


 a| 
Modification de l'abonnement impossible
 a| 
L'option permettant de modifier la capacité engagée pour les abonnements Keystone est actuellement indisponible dans la NetApp Console. Cette fonctionnalité sera réintroduite dans une future version.
 a| 
Aucune



 a| 
Facture incorrecte en raison d'une incompatibilité des données
 a| 
Une incohérence dans les données de consommation pour les abonnements AutoSupport entraîne la génération de factures incorrectes, ce qui entraîne des imprécisions de facturation.
 a| 
Aucune



 a| 
Affichage du type de politique QoS incorrect
 a| 
Dans l'onglet *Détails du volume*, la colonne *QoS Policy Type* affiche _QoS_ lorsqu'aucune stratégie QoS n'est appliquée, et la colonne compatible affiche _NOT SET_, ce qui provoque une incohérence dans l'état de la stratégie QoS affichée.
 a| 
Aucune



 a| 
Détails de volume non disponibles pour les abonnements principaux et liés
 a| 
L'onglet *Volume Summary* affiche zéro pour le nombre total de volumes, l'état de conformité QoS, le nombre de volumes protégés et la capacité totale consommée pour les abonnements principaux et secondaires liés.
 a| 
Aucune

|===