---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: 'Les problèmes connus identifient les problèmes susceptibles de vous empêcher d"utiliser efficacement les services d"abonnement Keystone.' 
---
= Problèmes connus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les problèmes connus identifient les problèmes susceptibles de vous empêcher d'utiliser efficacement les services d'abonnement Keystone.

Les problèmes connus suivants sont rapportés dans NetApp Keystone STaaS :

[cols="3*"]
|===
| Problème connu | Description | Solution de contournement 


 a| 
Détails de volume non disponibles pour les abonnements principaux et liés
 a| 
L'onglet *Volume Summary* affiche zéro pour le nombre total de volumes, l'état de conformité QoS, le nombre de volumes protégés et la capacité totale consommée pour les abonnements principaux et secondaires liés.
 a| 
Aucune



 a| 
Impossible de générer des rapports pour les abonnements
 a| 
Lorsque plus de 10-12 abonnements sont sélectionnés dans l'onglet *abonnements* de la page *abonnements Keystone*, le rapport ne peut pas être généré en cliquant sur le bouton *Télécharger CSV* avec l'option *inclure les données pour chaque niveau de service*.
 a| 
Aucune

|===