---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp vous offre des fonctionnalités nouvelles et améliorées dans chaque version des services de stockage en tant que service Keystone. 
---
= Nouveautés du stockage en tant que service Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp vous offre des fonctionnalités nouvelles et améliorées dans chaque version des services de stockage en tant que service Keystone.

Les améliorations suivantes sont introduites dans l'écran *abonnements Keystone* du conseiller digital Active IQ (également appelé conseiller digital) :



== 8 janvier 2025



=== Ajout d'options d'affichage de l'utilisation quotidienne des données accumulées

Vous pouvez désormais afficher l'utilisation quotidienne des données de dépassement accumulées sous forme de graphique ou de tableau pour une période de facturation mensuelle ou trimestrielle en cliquant sur la barre qui affiche les données facturées. Pour en savoir plus, reportez-vous link:../integrations/capacity-trend-tab.html#view-daily-accrued-burst-data-usage["Afficher l'utilisation quotidienne des données de bursting accumulées"]à la section .



== 12 décembre 2024



=== Colonne utilisé logique renommée

La colonne *logique utilisée* de l'onglet *Détails du volume* dans *volumes et objets* est maintenant renommée *Keystone logique utilisée*.



=== Onglet Ressources améliorées

L'onglet *Assets* de l'écran *abonnements Keystone* comporte maintenant deux nouveaux sous-onglets : *ONTAP* et *StorageGRID*. Ces sous-onglets offrent des informations détaillées au niveau du cluster pour ONTAP et des informations au niveau du grid pour StorageGRID en fonction de vos abonnements. Pour en savoir plus, reportez-vous link:../integrations/assets-tab.html["Onglet actifs"^]à la section .



=== Nouvelle option Masquer/Afficher les colonnes

L'onglet *Détails du volume* de *volumes et objets* inclut désormais une option *Masquer/Afficher les colonnes*. Cette option vous permet de sélectionner ou de désélectionner des colonnes pour personnaliser la liste tabulaire des volumes en fonction de vos préférences. Pour en savoir plus, reportez-vous link:../integrations/volumes-objects-tab.html["Volumes  amp; objets"^]à la section .



== 21 novembre 2024



=== Augmentation supplémentaire facturée

Vous pouvez maintenant afficher les données d'utilisation de dépassement accumulées sur une base trimestrielle via l'option *facturé cumulé Burst* si vous avez opté pour une période de facturation trimestrielle. Pour en savoir plus, reportez-vous link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst["Afficher les frais supplémentaires facturés"^]à la section .



=== Nouvelles colonnes de l'onglet Détails des volumes

Pour améliorer la clarté du calcul de l'utilisation logique, deux nouvelles colonnes ont été ajoutées à l'onglet *Détails du volume* dans l'onglet *volumes et objets* :

* *AFS logique* : affiche la capacité logique utilisée par le système de fichiers actif du volume.
* *Instantané physique* : affiche l'espace physique utilisé par les instantanés.


Ces colonnes offrent une meilleure clarté dans la colonne *logique utilisée*, qui indique la capacité logique combinée utilisée par le système de fichiers actif du volume et l'espace physique utilisé par les snapshots.



== 11 novembre 2024



=== Génération de rapports améliorée

Vous pouvez désormais générer un rapport consolidé pour afficher les détails de vos données Keystone à l'aide de la fonctionnalité de rapport de Digital Advisor. Pour en savoir plus, reportez-vous link:../integrations/aiq-keystone-details.html#generate-consolidated-report["Générer un rapport consolidé"^]à la section .



== 10 juillet 2024



=== Modifications de libellé

Le libellé *utilisation actuelle* est remplacé par *consommation actuelle* et *tendance capacité* est remplacé par *tendance consommation*.



=== Barre de recherche pour les abonnements

Le menu déroulant *abonnements* de tous les onglets de l'écran *abonnements Keystone* comprend désormais une barre de recherche. Vous pouvez rechercher des abonnements spécifiques répertoriés dans la liste déroulante *abonnements*.



== 27 juin 2024



=== Affichage cohérent de l'abonnement

L'écran *abonnements Keystone* est mis à jour pour afficher le numéro d'abonnement sélectionné dans tous les onglets.

* Lorsqu'un onglet de l'écran *abonnements Keystone* est actualisé, l'écran navigue automatiquement jusqu'à l'onglet *abonnements* et réinitialise tous les onglets au premier abonnement répertorié dans la liste déroulante *abonnement*.
* Si l'abonnement sélectionné n'est pas abonné aux mesures de performances, l'onglet *Performance* affiche le premier abonnement répertorié dans la liste déroulante *abonnement* lors de la navigation.




== 29 mai 2024



=== Indicateur de rafale amélioré

L'indicateur *Burst* dans l'index du graphique d'utilisation est amélioré pour afficher la valeur du pourcentage de limite de rafale. Cette valeur varie en fonction de la limite de capacité supplémentaire convenue pour un abonnement. Vous pouvez également afficher la valeur de la limite de rafale dans l'onglet *abonnements* en survolant l'indicateur *Burst usage* dans la colonne *Etat d'utilisation*.



=== Ajout de niveaux de service

Les niveaux de service *CVO Primary* et *CVO Secondary* sont inclus pour prendre en charge Cloud Volumes ONTAP pour les abonnements avec des plans tarifaires sans capacité allouée ou ceux configurés avec un cluster métropolitain.

* Vous pouvez afficher le graphique d'utilisation de la capacité pour ces niveaux de service à partir de l'ancien tableau de bord du widget *Keystone Subscriptions* et de l'onglet *Capacity Trend*, ainsi que des informations détaillées sur l'utilisation à partir de l'onglet *Current usage*.
* Dans l'onglet *abonnements*, ces niveaux de service sont affichés sous la forme `CVO (v2)` Dans la colonne *Type d'utilisation*, permettant l'identification de la facturation en fonction de ces niveaux de service.




=== Fonction de zoom avant pour les pics à court terme

L'onglet *Capacity Trend* inclut désormais une fonction de zoom avant pour afficher les détails des pics à court terme dans les graphiques d'utilisation. Pour plus d'informations, voir link:../integrations/capacity-trend-tab.html["Onglet tendances de capacité"^].



=== Affichage amélioré des abonnements

L'affichage par défaut des abonnements est amélioré pour trier par ID de suivi. Les abonnements de l'onglet *abonnements*, y compris dans la liste déroulante *abonnement* et les rapports CSV, seront maintenant affichés en fonction de la séquence alphabétique des ID de suivi, suivant l'ordre de a, A, b, B, etc.



=== Affichage amélioré de la rafale accumulée

L'info-bulle qui apparaît lorsque vous passez le curseur sur le graphique à barres d'utilisation de la capacité dans l'onglet *Capacity Trend* affiche désormais le type de rafale accumulée en fonction de la capacité allouée. Il établit une distinction entre les rafales cumulées provisoires et facturées, indiquant *la consommation cumulée provisoire* et *la consommation cumulée facturée* pour les abonnements avec des plans à taux de capacité engagée zéro, et *la capacité cumulée provisoire* et *la capacité cumulée facturée* pour ceux dont la capacité allouée n'est pas égale à zéro.



== 09 mai 2024



=== Nouvelles colonnes dans les rapports CSV

Les rapports CSV de l'onglet *Capacity Trend* incluent désormais les colonnes *Subscription Number* et *Account Name* pour plus de détails.



=== Colonne Type d'utilisation améliorée

La colonne *Type d'utilisation* de l'onglet *abonnements* est améliorée pour afficher les utilisations logiques et physiques sous forme de valeurs séparées par des virgules pour les abonnements qui couvrent les niveaux de service pour les fichiers et les objets.



=== Accédez aux détails du stockage objet à partir de l'onglet Détails du volume

L'onglet *Détails du volume* de l'onglet *volumes et objets* fournit désormais des détails sur le stockage d'objet ainsi que des informations sur le volume pour les abonnements qui incluent des niveaux de service pour le fichier et l'objet. Vous pouvez cliquer sur le bouton *Détails du stockage objet* dans l'onglet *Détails du volume* pour afficher les détails.



== 28 mars 2024



=== L'amélioration de la conformité à la règle QoS s'affiche dans l'onglet Détails du volume

L'onglet *Détails du volume* de l'onglet *volumes et objets* offre désormais une meilleure visibilité sur la conformité aux règles de qualité de service (QoS). La colonne précédemment connue sous le nom de *AQoS* est renommée *compatible*, ce qui indique si la stratégie QoS est conforme. En outre, une nouvelle colonne *QoS Policy Type* est ajoutée, qui indique si la règle est fixe ou adaptative. Si aucune de ces deux conditions ne s'applique, la colonne affiche _not available_. Pour plus d'informations, voir link:../integrations/volumes-objects-tab.html["Volumes  amp; objets"^].



=== Nouvelle colonne et affichage simplifié de l'abonnement dans l'onglet Volume Summary

* L'onglet *Volume Summary* de l'onglet *volumes et objets* inclut désormais une nouvelle colonne intitulée *Protected*. Cette colonne indique le nombre de volumes protégés associés aux niveaux de service auxquels vous êtes abonné. Si vous cliquez sur le nombre de volumes protégés, vous accédez à l'onglet *Détails du volume*, où vous pouvez afficher une liste filtrée de volumes protégés.
* L'onglet *Volume Summary* est mis à jour pour afficher uniquement les abonnements de base, à l'exclusion des services complémentaires. Pour plus d'informations, voir link:../integrations/volumes-objects-tab.html["Volumes  amp; objets"^].




=== Passez à l'affichage détaillé des rafales accumulées dans l'onglet tendance de capacité

L'info-bulle qui s'affiche lorsque vous passez le curseur sur le graphique à barres d'utilisation de la capacité dans l'onglet *Capacity Trend* affiche les détails des rafales accumulées pour le mois en cours. Les détails ne seront pas disponibles pour les mois précédents.



=== Accès amélioré pour afficher les données historiques des abonnements Keystone

Vous pouvez désormais afficher les données historiques en cas de modification ou de renouvellement d'un abonnement Keystone. Vous pouvez définir la date de début d'un abonnement à une date précédente pour afficher :

* Données relatives à la consommation et à l'utilisation des pics accumulés dans l'onglet *Capacity Trend*,
* Mesures de performances des volumes ONTAP à partir de l'onglet *Performance*,


tous affichent les données en fonction de la date sélectionnée de l'abonnement.



== 29 février 2024



=== Ajout de l'onglet actifs

L'écran *abonnements Keystone* comprend maintenant l'onglet *actifs*. Ce nouvel onglet fournit des informations au niveau du cluster en fonction de vos abonnements. Pour plus d'informations, voir link:../integrations/assets-tab.html["Onglet actifs"^].



=== Améliorations apportées à l'onglet volumes et objets

Pour plus de clarté sur les volumes de votre système ONTAP, deux nouveaux boutons d'onglet, *Volume Summary* et *Volume Details*, ont été ajoutés à l'onglet *volumes*. L'onglet *Volume Summary* fournit un nombre global de volumes associés aux niveaux de service auxquels vous êtes abonné, y compris leur état de conformité AQoS et leurs informations de capacité. L'onglet *Détails du volume* répertorie tous les volumes et leurs détails. Pour plus d'informations, voir link:../integrations/volumes-objects-tab.html["Volumes  amp; objets"^].



=== Expérience de recherche améliorée sur Digital Advisor

Les paramètres de recherche de l'écran *Digital Advisor* incluent désormais les numéros d'abonnement Keystone et les listes de contrôle créées pour les abonnements Keystone. Vous pouvez entrer les trois premiers caractères d'un numéro d'abonnement ou d'un nom de liste de contrôle. Pour plus d'informations, voir link:../integrations/keystone-aiq.html["Affichez le tableau de bord Keystone sur le conseiller digital Active IQ"^].



=== Afficher l'horodatage des données de consommation

Vous pouvez afficher l'horodatage des données de consommation (UTC) dans l'ancien tableau de bord du widget *Keystone Subscriptions*.



== 13 février 2024



=== Possibilité d'afficher les abonnements liés à un abonnement principal

Certains de vos abonnements principaux peuvent avoir des abonnements secondaires liés. Si c'est le cas, le numéro d'abonnement principal continuera d'être affiché dans la colonne *Numéro d'abonnement*, tandis que les numéros d'abonnement liés seront répertoriés dans une nouvelle colonne *abonnements liés* dans l'onglet *abonnements*. La colonne *abonnements liés* devient disponible uniquement si vous avez des abonnements liés, et vous pouvez voir des messages d'information vous en informer.



== 11 janvier 2024



=== Données facturées renvoyées pour le cumul de capacité supplémentaire

Les étiquettes de *Accrued Burst* sont maintenant modifiées en *facturé Burst cumulé* dans l'onglet *Capacity Trend*. La sélection de cette option vous permet d'afficher les graphiques mensuels des données de dépassement cumulées facturées. Pour plus d'informations, voir link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst["Afficher les frais supplémentaires facturés"^].



=== Détails de la consommation cumulée pour des plans tarifaires spécifiques

Si vous disposez d'un abonnement avec des abonnements ayant une capacité allouée _zéro_, vous pouvez afficher les détails de la consommation accumulée dans l'onglet *Capacity Trend*. Lorsque vous sélectionnez l'option *consommation cumulée facturée*, vous pouvez afficher les graphiques mensuels des données de consommation accumulée facturées.



== 15 décembre 2023



=== Possibilité de rechercher par listes de surveillance

La prise en charge des listes de suivi dans Digital Advisor a été étendue aux systèmes Keystone. Vous pouvez maintenant afficher les détails des abonnements de plusieurs clients en effectuant une recherche à l'aide de listes de contrôle. Pour plus d'informations sur l'utilisation des listes de suivi dans Keystone STaaS, consultez la section link:../integrations/keystone-aiq.html#search-by-keystone-watchlists["Rechercher par listes de surveillance Keystone"^].



=== Date convertie en fuseau horaire UTC

Les données renvoyées dans les onglets de l'écran *Keystone Subscriptions* de Digital Advisor s'affichent en heure UTC (fuseau horaire du serveur). Lorsque vous saisissez une date pour la requête, elle est automatiquement considérée comme étant en heure UTC. Pour plus d'informations, voir link:../integrations/aiq-keystone-details.html["Tableau de bord et reporting des abonnements Keystone"^].
