---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nouvelles fonctionnalités et améliorations de Keystone STaaS 
---
= Nouveautés du stockage en tant que service Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp vous offre des fonctionnalités nouvelles et améliorées dans chaque version des services de stockage en tant que service Keystone.



== Nouvelles fonctionnalités et améliorations pour le 11 janvier 2024

Découvrez les nouveautés de cette version.

Les modifications suivantes ont été effectuées sur l'écran *abonnements Keystone* du conseiller numérique Active IQ (également appelé Conseiller numérique).



=== Données facturées renvoyées pour le cumul de capacité supplémentaire

Les étiquettes de *Accrued Burst* sont maintenant modifiées en *facturé Burst cumulé* dans l'onglet *Capacity Trend*. La sélection de cette option vous permet d'afficher les graphiques mensuels des données de dépassement cumulées facturées. Pour plus d'informations, voir link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Afficher les frais supplémentaires facturés"^].



=== Détails de la consommation cumulée pour des plans tarifaires spécifiques

Si vous disposez d'un abonnement avec des abonnements ayant une capacité allouée _zéro_, vous pouvez afficher les détails de la consommation accumulée dans l'onglet *Capacity Trend*. Lorsque vous sélectionnez l'option *consommation cumulée facturée*, vous pouvez afficher les graphiques mensuels des données de consommation accumulée facturées.



== Nouvelles fonctionnalités et améliorations pour le 15 décembre 2023

Découvrez les nouveautés de cette version.



=== Possibilité de rechercher par listes de surveillance

La prise en charge des listes de suivi dans Active IQ Digital Advisor (également appelé Digital Advisor) a été étendue aux systèmes Keystone. Vous pouvez maintenant afficher les détails des abonnements de plusieurs clients en effectuant une recherche à l'aide de listes de contrôle. Pour plus d'informations sur l'utilisation des listes de suivi dans Keystone STaaS, voir link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Effectuez une recherche à l'aide des listes de surveillance Keystone"^].



=== Date convertie en fuseau horaire UTC

Les données renvoyées dans les onglets de l'écran *abonnements Keystone* de Active IQ Digital Advisor s'affichent en heure UTC (fuseau horaire du serveur). Lorsque vous saisissez une date pour la requête, elle est automatiquement considérée comme étant en heure UTC. Pour plus d'informations, voir link:../integrations/aiq-keystone-details.html["Tableau de bord et reporting des abonnements Keystone"^].
