---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nouvelles fonctionnalités et améliorations de Keystone STaaS 
---
= Nouveautés du stockage en tant que service Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp vous offre des fonctionnalités nouvelles et améliorées dans chaque version des services de stockage en tant que service Keystone.



== Nouvelles fonctionnalités et améliorations pour le 29 février 2024

Plusieurs améliorations ont été apportées au tableau de bord Active IQ Digital Advisor (également appelé Digital Advisor) et à l'écran *abonnements Keystone* pour cette version :



=== Ajout de l'onglet actifs

L'écran *abonnements Keystone* comprend maintenant l'onglet *actifs*. Ce nouvel onglet fournit des informations au niveau du cluster en fonction de vos abonnements. Pour plus d'informations, voir link:../integrations/assets-tab.html["Onglet actifs"^].



=== Améliorations apportées à l'onglet volumes et objets

Pour plus de clarté sur les volumes de votre système ONTAP, deux nouveaux boutons d'onglet, *Volume Summary* et *Volume Details*, ont été ajoutés à l'onglet *volumes*. L'onglet *Volume Summary* fournit un nombre global de volumes associés aux niveaux de service auxquels vous êtes abonné, y compris leur état de conformité AQoS et leurs informations de capacité. L'onglet *Détails du volume* répertorie tous les volumes et leurs détails. Pour plus d'informations, voir link:../integrations/volumes-objects-tab.html["Volumes  amp; objets"^].



=== Expérience de recherche améliorée sur Digital Advisor

Les paramètres de recherche de l'écran *Digital Advisor* incluent désormais les numéros d'abonnement Keystone et les listes de contrôle créées pour les abonnements Keystone. Vous pouvez entrer les trois premiers caractères d'un numéro d'abonnement ou d'un nom de liste de contrôle. Pour plus d'informations, voir link:../integrations/keystone-aiq.html["Affichez le tableau de bord Keystone sur le conseiller digital Active IQ"^].



=== Afficher l'horodatage des données de consommation

Vous pouvez afficher l'horodatage des données de consommation (UTC) dans l'ancien tableau de bord du widget *Keystone Subscriptions*.



== Nouvelles fonctionnalités et améliorations pour le 13 février 2024

L'amélioration suivante a été apportée à l'écran *abonnements Keystone* du conseiller numérique Active IQ (également appelé Conseiller numérique).



=== Possibilité d'afficher les abonnements liés à un abonnement principal

Certains de vos abonnements principaux peuvent avoir des abonnements secondaires liés. Si c'est le cas, le numéro d'abonnement principal continuera d'être affiché dans la colonne *Numéro d'abonnement*, tandis que les numéros d'abonnement liés seront répertoriés dans une nouvelle colonne *abonnements liés* dans l'onglet *abonnements*. La colonne *abonnements liés* devient disponible uniquement si vous avez des abonnements liés, et vous pouvez voir des messages d'information vous en informer.



== Nouvelles fonctionnalités et améliorations pour le 11 janvier 2024

Découvrez les nouveautés de cette version.

Les améliorations suivantes ont été apportées à l'écran *abonnements Keystone* de Active IQ Digital Advisor (également appelé Conseiller numérique).



=== Données facturées renvoyées pour le cumul de capacité supplémentaire

Les étiquettes de *Accrued Burst* sont maintenant modifiées en *facturé Burst cumulé* dans l'onglet *Capacity Trend*. La sélection de cette option vous permet d'afficher les graphiques mensuels des données de dépassement cumulées facturées. Pour plus d'informations, voir link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Afficher les frais supplémentaires facturés"^].



=== Détails de la consommation cumulée pour des plans tarifaires spécifiques

Si vous disposez d'un abonnement avec des abonnements ayant une capacité allouée _zéro_, vous pouvez afficher les détails de la consommation accumulée dans l'onglet *Capacity Trend*. Lorsque vous sélectionnez l'option *consommation cumulée facturée*, vous pouvez afficher les graphiques mensuels des données de consommation accumulée facturées.



== Nouvelles fonctionnalités et améliorations pour le 15 décembre 2023

Découvrez les nouveautés de cette version.



=== Possibilité de rechercher par listes de surveillance

La prise en charge des listes de suivi dans Active IQ Digital Advisor (également appelé Digital Advisor) a été étendue aux systèmes Keystone. Vous pouvez maintenant afficher les détails des abonnements de plusieurs clients en effectuant une recherche à l'aide de listes de contrôle. Pour plus d'informations sur l'utilisation des listes de suivi dans Keystone STaaS, voir link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Effectuez une recherche à l'aide des listes de surveillance Keystone"^].



=== Date convertie en fuseau horaire UTC

Les données renvoyées dans les onglets de l'écran *abonnements Keystone* de Active IQ Digital Advisor s'affichent en heure UTC (fuseau horaire du serveur). Lorsque vous saisissez une date pour la requête, elle est automatiquement considérée comme étant en heure UTC. Pour plus d'informations, voir link:../integrations/aiq-keystone-details.html["Tableau de bord et reporting des abonnements Keystone"^].
